package pluginhost

import (
	"crypto/sha256"
)

// Assembly of the signed Sigil block (ADR-026, slice S3).
//
// This file is a shared helper imported by BOTH sides of the trust seal:
//   - keeper/internal/sigil (S3) — when signing an artifact;
//   - soul/internal/pluginhost (S6) — when verifying before seal/exec.
//
// Placed in shared/pluginhost because that package is already imported by both keeper
// and soul (see who-imports) and depends only on shared/plugin + grpc — no import
// cycle.
//
// # What the block identifies
//
// The artifact carries no self-name (NIM-377): no namespace, no name, no publisher.
// The only identity it can be signed under is the one the operator asserted when
// approving it — the SOURCE it came from, at a REF. The registration alias is
// deliberately NOT in the block: an alias is a local naming choice, so registering the
// same bytes a second time under a second alias must not require a second signature,
// and forging an alias must not be able to reach a signature at all.
//
// # S3↔S6 invariant (normative)
//
// The schema-document bytes Keeper hashes at Sign MUST equal the bytes Soul re-hashes
// at verify. The guarantee is now structural rather than negotiated: the document is
// canonical JSON produced by one serializer (`sdk/schema`.Marshal — sorted keys, no
// insignificant whitespace), and it travels with the artifact. There is nothing left
// to normalize, so there is no normalization step to disagree about — both sides call
// [SchemaDigest] on the bytes they hold and get the same 32 bytes or a mismatch that
// means the bytes really differ.

// sigilDomainSeparator — domain-separation tag of the signed Sigil block.
//
// The `/v2` version is mandatory: on a block-format change the tag moves, and old
// signatures stop verifying against the new code — an explicit, not silent,
// compatibility break. v1 keyed on (namespace, name); NIM-377 removed both from the
// artifact and re-keyed the block on the source, so v1 signatures must not verify
// here. The tag is placed first in the block so a Sigil signature cannot be reused in
// another protocol (cross-protocol signature reuse).
const sigilDomainSeparator = "soul-stack/sigil/v2"

// SchemaDigest is the SHA-256 of a canonical schema document, and the ONE function
// both sides of the seal call.
//
// It takes the bytes as they are. The document is generated by a single serializer and
// is byte-deterministic by construction, so there is no BOM, no line-ending and no
// trailing-whitespace variance to absorb — and a "canonicalize before hashing" step
// would only create a place where the two sides could implement the same idea
// differently. Two documents that differ by one byte are two different documents.
func SchemaDigest(schemaDoc []byte) [32]byte { return sha256.Sum256(schemaDoc) }

// BuildSigilBlock assembles the deterministic signed Sigil block from the fields of an
// allow-list entry (ADR-026(b)/(c)). Pure function: one input → one output, no
// proto-marshal (a SigilSignedBlock message is deliberately NOT introduced — it would
// reintroduce proto-serialization nondeterminism, R-det).
//
// Block form (field order is fixed, cannot change without bumping the DST to v3):
//
//	DST || LP(source) || LP(ref) || LP(binarySHA256Raw) || LP(schemaSHA256Raw)
//
// where:
//   - DST = the ASCII constant [sigilDomainSeparator] ("soul-stack/sigil/v2"),
//     added WITHOUT a length-prefix (a fixed known prefix);
//   - source = the artifact source the operator approved (the git remote of the module
//     repository), and ref the revision within it. Together they are the artifact's
//     only signed identity;
//   - LP(x) = 4 bytes big-endian uint32 length of x, then the bytes of x. LP is
//     applied to EVERY variable field — this protects field boundaries: without a
//     length-prefix the concatenation ("ab","c") and ("a","bc") would yield the same
//     block, and a signature over one field set would fit another;
//   - hashes are stored as RAW bytes (32 bytes for SHA-256), NOT a hex string.
//     schemaSHA256Raw comes from [SchemaDigest].
//
// Field order is exactly: source, ref, binary_sha256, schema_sha256.
func BuildSigilBlock(source, ref string, binarySHA256Raw, schemaSHA256Raw []byte) []byte {
	const lpSize = 4
	dst := []byte(sigilDomainSeparator)

	total := len(dst) +
		lpSize + len(source) +
		lpSize + len(ref) +
		lpSize + len(binarySHA256Raw) +
		lpSize + len(schemaSHA256Raw)

	block := make([]byte, 0, total)
	block = append(block, dst...)
	block = appendLP(block, []byte(source))
	block = appendLP(block, []byte(ref))
	block = appendLP(block, binarySHA256Raw)
	block = appendLP(block, schemaSHA256Raw)
	return block
}

// appendLP appends a length-prefixed field: uint32 big-endian length + bytes.
func appendLP(dst, field []byte) []byte {
	n := uint32(len(field))
	dst = append(dst, byte(n>>24), byte(n>>16), byte(n>>8), byte(n))
	return append(dst, field...)
}
