package console

import (
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"

	keeperv1 "github.com/souls-guild/soul-stack/proto/gen/go/keeper/v1"
)

// Wire protocol of the browser<->Keeper console socket (`/v1/console`).
//
// Frames are JSON text and mirror the Keeper<->Soul `console_*` oneofs 1:1, so
// Keeper relays rather than translates. Byte payloads are base64: a pty carries
// arbitrary bytes (ANSI escapes, partial UTF-8 runes, NUL) and JSON cannot hold
// them raw. The client-side half of this contract is
// `soul-stack-web/src/api/consoleProtocol.ts`; the full spec is
// docs/keeper/console.md.
//
// One socket multiplexes N sessions. `session_id` on the wire is generated by
// the CLIENT (so it can correlate `open` with `opened` without a round trip)
// and is only unique within that socket — Keeper mints its own ULID for the
// Soul side, where uniqueness must hold per EventStream. The translation is the
// session manager's job (see [Hub]); the two ids never leak into each other's
// half of the system.
const (
	// Subprotocol is offered by the client and MUST be echoed back as the
	// negotiated subprotocol, or the browser closes the socket.
	Subprotocol = "soul-stack.console.v1"

	// BearerSubprotocolPrefix carries the JWT as a second subprotocol offer,
	// since the browser WebSocket API cannot set an Authorization header. The
	// token is consumed by the auth middleware, never by this package.
	BearerSubprotocolPrefix = "bearer."
)

// Client -> Keeper frame types.
const (
	TypeOpen   = "open"
	TypeStdin  = "stdin"
	TypeResize = "resize"
	TypeClose  = "close"
)

// Keeper -> Client frame types.
const (
	TypeOpened = "opened"
	TypeChunk  = "chunk"
	TypeExit   = "exit"
	TypeError  = "error"
)

// Error codes carried by an `error` frame. Session-scoped when the frame has a
// `session_id`, socket-scoped otherwise. The set is closed and stable — the UI
// branches on it.
const (
	// ErrCodeBadFrame — malformed JSON, unknown type or a missing field.
	ErrCodeBadFrame = "bad_frame"
	// ErrCodeForbidden — RBAC refused this SID (the socket itself was allowed).
	ErrCodeForbidden = "forbidden"
	// ErrCodeSoulOffline — no EventStream for the SID anywhere in the cluster.
	ErrCodeSoulOffline = "soul_offline"
	// ErrCodeUnsupported — the Soul binary does not announce the `console`
	// capability. Fail-closed: an old binary would never answer ConsoleOpen.
	ErrCodeUnsupported = "console_unsupported"
	// ErrCodeLimitExceeded — the operator or this Keeper is at its session cap.
	ErrCodeLimitExceeded = "limit_exceeded"
	// ErrCodeDuplicateSession — the client reused a live session_id on this socket.
	ErrCodeDuplicateSession = "duplicate_session"
	// ErrCodeBusy — the Soul is connected, but the Keeper->Soul queue for it is
	// full. A console shares that queue (depth 10 per SID) with the apply cycle,
	// so a burst — many consoles typing at one host at once — can hit it. It is
	// explicitly NOT soul_offline: the host is healthy and the operator should
	// retry the keystroke, not go looking for a dead agent.
	ErrCodeBusy = "soul_busy"
	// ErrCodeRecordingUnavailable — the session could not be recorded, so it is
	// not opened, or an open one is closed. Recording is not optional
	// (ADR-0074(g)) and the operator cannot retry their way past it: this is
	// Keeper's storage being unreachable, not the host being busy. Reported as
	// its own code rather than folded into `internal` because it is the one
	// Keeper-side failure whose fix is "the audit store is down", and a
	// terminal that closed for that reason must not look like a crashed shell.
	ErrCodeRecordingUnavailable = "recording_unavailable"
	// ErrCodeInternal — Keeper-side failure (dispatch error, no Outbound wired).
	ErrCodeInternal = "internal"
)

// ClientFrame is the decoded browser->Keeper frame. One struct for all four
// types: the shapes barely differ and a discriminated decode would buy nothing
// but allocations on the keystroke path.
type ClientFrame struct {
	Type      string `json:"type"`
	SessionID string `json:"session_id"`
	SID       string `json:"sid,omitempty"`
	Data      string `json:"data,omitempty"` // base64
	Cols      uint32 `json:"cols,omitempty"`
	Rows      uint32 `json:"rows,omitempty"`
	Shell     string `json:"shell,omitempty"`
}

// ErrBadFrame marks a frame the client got wrong (as opposed to a Keeper-side
// failure). The caller answers with an `error` frame and keeps the socket.
var ErrBadFrame = errors.New("console: malformed client frame")

// DecodeClientFrame parses and validates one inbound frame.
//
// Validation is deliberately strict about `session_id`: without it a frame
// cannot be routed to a session, and silently dropping it would leave the
// operator typing into a terminal that answers nothing.
func DecodeClientFrame(raw []byte) (*ClientFrame, error) {
	var f ClientFrame
	if err := json.Unmarshal(raw, &f); err != nil {
		return nil, fmt.Errorf("%w: %v", ErrBadFrame, err)
	}
	if f.SessionID == "" {
		return nil, fmt.Errorf("%w: missing session_id", ErrBadFrame)
	}
	switch f.Type {
	case TypeOpen:
		if f.SID == "" {
			return nil, fmt.Errorf("%w: open without sid", ErrBadFrame)
		}
	case TypeStdin:
		if _, err := f.DecodeData(); err != nil {
			return nil, err
		}
	case TypeResize, TypeClose:
		// No extra required fields: a zero geometry is ignored downstream
		// (a resize is never a request for a 0-sized terminal), and close
		// carries nothing but the id.
	default:
		return nil, fmt.Errorf("%w: unknown type %q", ErrBadFrame, f.Type)
	}
	return &f, nil
}

// DecodeData returns the raw bytes of a base64 `data` field.
func (f *ClientFrame) DecodeData() ([]byte, error) {
	if f.Data == "" {
		return nil, nil
	}
	b, err := base64.StdEncoding.DecodeString(f.Data)
	if err != nil {
		return nil, fmt.Errorf("%w: data is not base64: %v", ErrBadFrame, err)
	}
	return b, nil
}

// --- Keeper -> client frames ---
//
// Separate types per frame rather than one struct with omitempty: `code` is a
// number on `exit` and a string on `error`, which one Go struct cannot express.

// OpenedFrame reports that the pty is live. Until it arrives the UI pane shows
// "connecting" and refuses input.
type OpenedFrame struct {
	Type      string `json:"type"`
	SessionID string `json:"session_id"`
	SID       string `json:"sid"`
	PID       int32  `json:"pid,omitempty"`
}

// ChunkFrame carries pty output.
//
// `dropped_bytes` is the sum of what BOTH flow-control stages discarded before
// this chunk — the Soul-side token bucket and the Keeper-side socket queue. It
// is additive-only for the UI (the current client ignores it); the field exists
// so a gap can be rendered explicitly rather than splicing a corrupted ANSI
// stream, which is the whole reason the drop is counted instead of hidden.
type ChunkFrame struct {
	Type         string `json:"type"`
	SessionID    string `json:"session_id"`
	Stream       string `json:"stream"`
	Data         string `json:"data"` // base64
	DroppedBytes uint64 `json:"dropped_bytes,omitempty"`
}

// ExitFrame is the single terminal frame of a session.
type ExitFrame struct {
	Type      string `json:"type"`
	SessionID string `json:"session_id"`
	Code      int32  `json:"code"`
	// Reason mirrors ConsoleExitReason in snake_case (`process_exited`,
	// `closed_by_keeper`, `open_failed`, `soul_shutdown`, `limit_exceeded`).
	// Additive to the client contract: an exit code of 0 from a shell the
	// operator never closed reads very differently from a clean `exit`.
	Reason string `json:"reason,omitempty"`
	// Message carries the Soul-side detail for a refused open.
	Message string `json:"message,omitempty"`
}

// ErrorFrame is session-scoped when SessionID is set, socket-scoped otherwise.
type ErrorFrame struct {
	Type      string `json:"type"`
	SessionID string `json:"session_id,omitempty"`
	Code      string `json:"code"`
	Message   string `json:"message"`
}

// NewOpened builds an `opened` frame.
func NewOpened(sessionID, sid string, pid int32) OpenedFrame {
	return OpenedFrame{Type: TypeOpened, SessionID: sessionID, SID: sid, PID: pid}
}

// NewChunk builds a `chunk` frame, base64-encoding the payload.
func NewChunk(sessionID string, stream keeperv1.ConsoleStream, data []byte, dropped uint64) ChunkFrame {
	return ChunkFrame{
		Type:         TypeChunk,
		SessionID:    sessionID,
		Stream:       streamName(stream),
		Data:         base64.StdEncoding.EncodeToString(data),
		DroppedBytes: dropped,
	}
}

// NewExit builds an `exit` frame.
func NewExit(sessionID string, code int32, reason keeperv1.ConsoleExitReason, message string) ExitFrame {
	return ExitFrame{
		Type:      TypeExit,
		SessionID: sessionID,
		Code:      code,
		Reason:    exitReasonName(reason),
		Message:   message,
	}
}

// NewError builds an `error` frame. An empty sessionID makes it socket-scoped.
func NewError(sessionID, code, message string) ErrorFrame {
	return ErrorFrame{Type: TypeError, SessionID: sessionID, Code: code, Message: message}
}

// streamName maps the proto enum to the wire string. A pty merges stdout and
// stderr onto one fd, so STDOUT is the only value seen in practice; UNSPECIFIED
// is normalized to stdout rather than surfaced, since the client's union has no
// third member and an unknown value would break its rendering.
func streamName(s keeperv1.ConsoleStream) string {
	if s == keeperv1.ConsoleStream_CONSOLE_STREAM_STDERR {
		return "stderr"
	}
	return "stdout"
}

// exitReasonName maps ConsoleExitReason to snake_case. UNSPECIFIED never
// appears in a real ConsoleExit and maps to an empty string (field omitted).
func exitReasonName(r keeperv1.ConsoleExitReason) string {
	switch r {
	case keeperv1.ConsoleExitReason_CONSOLE_EXIT_REASON_PROCESS_EXITED:
		return "process_exited"
	case keeperv1.ConsoleExitReason_CONSOLE_EXIT_REASON_CLOSED_BY_KEEPER:
		return "closed_by_keeper"
	case keeperv1.ConsoleExitReason_CONSOLE_EXIT_REASON_OPEN_FAILED:
		return "open_failed"
	case keeperv1.ConsoleExitReason_CONSOLE_EXIT_REASON_SOUL_SHUTDOWN:
		return "soul_shutdown"
	case keeperv1.ConsoleExitReason_CONSOLE_EXIT_REASON_LIMIT_EXCEEDED:
		return "limit_exceeded"
	default:
		return ""
	}
}
