// Package certissue — canonical issue-material for TLS certs: keypair+CSR
// generation, signing via Vault PKI, and cert+key write to Vault by E3 paths
// (NIM-99). Common foundation for reaper (auto-rotation) and coremod/cert (issue
// step): the issuance logic lives here so the two consumers don't diverge.
//
// * R2 invariant: the private key (privPEM) is generated by the Keeper, written only to
// Vault, and NEVER logged / put into audit / leaked into an error text
// (a deliberate exception from the identity invariant).
package certissue

import (
	"context"
	"crypto/x509"
	"encoding/pem"
	"fmt"
	"strings"
	"time"

	keepercert "github.com/souls-guild/soul-stack/keeper/internal/cert"
)

// SignedCert — result of the PKI signing (mirrors vault.SignedCertificate; the package
// doesn't pull in vault just for the type, the adapter converts it in wire-up).
type SignedCert struct {
	CertificatePEM []byte
	CAChainPEM     []byte
	SerialNumber   string
	NotAfter       time.Time
}

// Signer — narrow surface of the Vault PKI sign-RPC (vault.Client.SignCSR).
type Signer interface {
	SignCSR(ctx context.Context, mount, role, csrPEM string) (*SignedCert, error)
}

// KVWriter — narrow surface of the Vault KV write (vault.Client.WriteKV).
type KVWriter interface {
	WriteKV(ctx context.Context, path string, data map[string]any) error
}

// CSRGenFunc generates keypair+CSR (keeper-side, R2). Prod is a wrapper over
// vault.GenerateServiceCSR; tests substitute a deterministic fake.
type CSRGenFunc func(commonName string, dnsNames []string) (privPEM, csrPEM []byte, err error)

// Params — input to [Issue]: cert identity (CN/DNS), PKI coordinates (Mount/Role), and
// the E3 paths for writing the material to Vault (CertPath/KeyPath).
type Params struct {
	CommonName string
	DNSNames   []string
	Mount      string
	Role       string
	CertPath   string
	KeyPath    string
}

// Material — result of [Issue]: new cert+key + Vault refs (`<path>#field`) for
// warrant registration.
type Material struct {
	CertPEM      []byte
	KeyPEM       []byte
	SerialNumber string
	Fingerprint  string
	NotAfter     time.Time
	CertRef      string
	KeyRef       string
}

// VaultPath — E3 path of the incarnation's TLS material: secret/<service>/<incarnation>/tls/<kind>.
// Single source of convention for issuance (core.cert.issued) and rotation (Reaper):
// issue and rotate must build the SAME path, otherwise the cert is written to one and read
// from the other. For service="redis" matches the old hardcode (backcompat).
func VaultPath(service, incarnation string, kind keepercert.Kind) string {
	// Defense-in-depth: service/incarnation are validated identifiers; `/`,
	// `..`, or empty is a caller bug, otherwise the path would escape secret/<svc>/<inc>/.
	if !safeVaultSegment(service) || !safeVaultSegment(incarnation) {
		panic(fmt.Sprintf("certissue.VaultPath: unsafe segment (service=%q incarnation=%q)", service, incarnation))
	}
	return "secret/" + service + "/" + incarnation + "/tls/" + string(kind)
}

// safeVaultSegment rejects an empty segment and anything that could escape secret/
// (separator `/`, traversal `..`).
func safeVaultSegment(s string) bool {
	return s != "" && !strings.Contains(s, "/") && !strings.Contains(s, "..")
}

// Issue issues a TLS cert: csrgen(CN,DNS) → SignCSR → WriteKV(cert)+WriteKV(key)
// → fingerprint. CAChainPEM is discarded (CA is not rotated). * privPEM never leaks
// into an error text at any step (R2).
func Issue(ctx context.Context, s Signer, w KVWriter, csrgen CSRGenFunc, p Params) (*Material, error) {
	privPEM, csrPEM, err := csrgen(p.CommonName, p.DNSNames)
	if err != nil {
		return nil, fmt.Errorf("certissue: csrgen: %w", err)
	}

	signed, err := s.SignCSR(ctx, p.Mount, p.Role, string(csrPEM))
	if err != nil {
		return nil, fmt.Errorf("certissue: sign csr: %w", err)
	}

	// cert-PEM in the `cert` field, key-PEM in the `key` field (parity with the essence
	// convention tls_cert_ref "<path>#cert"). WriteKV never leaks values into an error text.
	if werr := w.WriteKV(ctx, p.CertPath, map[string]any{"cert": string(signed.CertificatePEM)}); werr != nil {
		return nil, fmt.Errorf("certissue: write cert to vault: %w", werr)
	}
	if werr := w.WriteKV(ctx, p.KeyPath, map[string]any{"key": string(privPEM)}); werr != nil {
		return nil, fmt.Errorf("certissue: write key to vault: %w", werr)
	}

	fingerprint, err := fingerprintFromPEM(signed.CertificatePEM)
	if err != nil {
		return nil, fmt.Errorf("certissue: fingerprint new cert: %w", err)
	}

	return &Material{
		CertPEM:      signed.CertificatePEM,
		KeyPEM:       privPEM,
		SerialNumber: signed.SerialNumber,
		Fingerprint:  fingerprint,
		NotAfter:     signed.NotAfter.UTC(),
		CertRef:      p.CertPath + "#cert",
		KeyRef:       p.KeyPath + "#key",
	}, nil
}

// fingerprintFromPEM parses the first CERTIFICATE PEM block and computes the fingerprint
// SHA-256(SubjectPublicKeyInfo) via [keepercert.FingerprintFromCert].
func fingerprintFromPEM(pemBytes []byte) (string, error) {
	rest := pemBytes
	for {
		var block *pem.Block
		block, rest = pem.Decode(rest)
		if block == nil {
			return "", fmt.Errorf("certissue: no CERTIFICATE block in PEM")
		}
		if block.Type == "CERTIFICATE" {
			cert, err := x509.ParseCertificate(block.Bytes)
			if err != nil {
				return "", fmt.Errorf("certissue: parse certificate: %w", err)
			}
			return keepercert.FingerprintFromCert(cert), nil
		}
	}
}
