// Package cert — Warrant registry (`warrant`): issued SERVICE TLS materials
// of incarnations under cert-rotation Var1 (Keeper-centric). The Reaper rule
// `rotate_due_certs` scans on `not_after`.
//
// ★ DIFFERENCE FROM soulseed (`soul_seeds`, docs/soul/identity.md): soul_seeds
// are IDENTITY certs of Soul agents, where the private key NEVER leaves the
// host (only the fingerprint is in the DB). Warrant is SERVICE certs (e.g.
// server TLS for Redis), where the private key is GENERATED by Keeper
// centrally (R2, keeper/internal/vault/csrgen.go) and passes through
// Keeper → Vault. This is a deliberate exception to the identity model's
// invariant "the private key never leaves the host": a service cert is not
// an identity cert, and it already lives in Vault for manual rotate_tls.
// The decision is recorded in a separate cert-rotation ADR. The private key
// is NOT stored in the DB — only vault_ref + fingerprint + serial.
//
// One (incarnation, kind) has many warrant rows (rotation history); exactly
// one active per kind at a time is guaranteed by the partial unique
// `warrant_active_by_incarnation_kind_idx`.
package cert

import (
	"crypto/sha256"
	"crypto/x509"
	"encoding/hex"
	"errors"
	"time"
)

// Kind — type of TLS material of a Warrant row. Matches the CHECK
// `warrant_kind_valid` from 092_create_warrant.up.sql.
//
//   - `cert` — server certificate (redis.crt).
//   - `key`  — private key (redis.key). not_after duplicates cert (one pair).
//   - `ca`   — cluster CA certificate (ca.crt).
type Kind string

const (
	KindCert Kind = "cert"
	KindKey  Kind = "key"
	KindCA   Kind = "ca"
)

// Status — state of a row in the registry. Matches the CHECK
// `warrant_status_valid`.
//
//   - `active`     — currently issued material, exactly one per (incarnation, kind).
//   - `superseded` — replaced by rotation, the new active is already written.
//   - `expired`    — moved past not_after (post-MVP mover; for now — purge cleanup).
//   - `rotating`   — CAS-marked by the Reaper rule `rotate_due_certs` for the
//     duration of the rotation chain (single-winner barrier against a double
//     Voyage spawn).
//   - `failed`     — the rotation chain failed (SignCSR/WriteKV/Voyage-insert):
//     the row stays outside active so the next tick doesn't consider it due
//     and loop.
type Status string

const (
	StatusActive     Status = "active"
	StatusSuperseded Status = "superseded"
	StatusExpired    Status = "expired"
	StatusRotating   Status = "rotating"
	StatusFailed     Status = "failed"
)

// FingerprintHexLen — length of the hex representation of a SHA-256
// fingerprint (64). Symmetric to soulseed.FingerprintHexLen.
const FingerprintHexLen = 64

// Sentinel errors of the CRUD layer.
var (
	// ErrInvalidFingerprint — fingerprint is not 64 lower-hex. Duplicates the
	// CHECK `warrant_fingerprint_format`.
	ErrInvalidFingerprint = errors.New("cert: fingerprint format invalid (must be 64 lower-hex chars)")
)

// Warrant — runtime representation of a row in the `warrant` registry.
//
// The private key and PEM do NOT live here (protection is Vault, field
// VaultRef). fingerprint is SHA-256(SubjectPublicKeyInfo) — same class as
// soulseed.
type Warrant struct {
	CertID                  string         `json:"cert_id"`
	IncarnationID           string         `json:"incarnation_id"`
	Kind                    Kind           `json:"kind"`
	VaultRef                string         `json:"vault_ref"`
	SerialNumber            string         `json:"serial_number"`
	Fingerprint             string         `json:"fingerprint"`
	NotAfter                time.Time      `json:"not_after"`
	IssuedAt                time.Time      `json:"issued_at"`
	PKIMount                *string        `json:"pki_mount,omitempty"`
	PKIRole                 *string        `json:"pki_role,omitempty"`
	Status                  Status         `json:"status"`
	IssuedByKID             *string        `json:"issued_by_kid,omitempty"`
	LastRotationVoyageID    *string        `json:"last_rotation_voyage_id,omitempty"`
	AutoRotate              bool           `json:"auto_rotate"`
	RotateThresholdOverride *time.Duration `json:"rotate_threshold_override,omitempty"`
}

// FingerprintFromCert computes the SHA-256 fingerprint of the certificate's
// public key (DER SubjectPublicKeyInfo) — bound to the key, not the whole
// DER cert. Symmetric to soulseed.FingerprintFromCert.
func FingerprintFromCert(cert *x509.Certificate) string {
	sum := sha256.Sum256(cert.RawSubjectPublicKeyInfo)
	return hex.EncodeToString(sum[:])
}

// ValidFingerprintFormat — format check (64 lower-hex). Caller validates
// before the round-trip; PG CHECK backs it up on the DB side.
func ValidFingerprintFormat(fp string) bool {
	if len(fp) != FingerprintHexLen {
		return false
	}
	for _, c := range fp {
		if (c < '0' || c > '9') && (c < 'a' || c > 'f') {
			return false
		}
	}
	return true
}

func validKind(k Kind) bool {
	switch k {
	case KindCert, KindKey, KindCA:
		return true
	}
	return false
}

func validStatus(s Status) bool {
	switch s {
	case StatusActive, StatusSuperseded, StatusExpired, StatusRotating, StatusFailed:
		return true
	}
	return false
}
