-- 092_create_warrant.up.sql
--
-- Registry of Warrant - issued SERVICE TLS certs for incarnations (not identity!)
-- under cert-rotation Variant 1 (Keeper-centric). The scan axis for the Reaper rule
-- `rotate_due_certs` is `not_after`: certs whose expiry falls within the
-- threshold are rotated centrally (Keeper generates a new keypair+CSR,
-- SignCSR via Vault PKI, WriteKV into Vault, spawns the day-2 Voyage scenario
-- rotate_tls).
--
-- ★ DIFFERENCE FROM soul_seeds (009): soul_seeds are Soul agents' IDENTITY certs
-- (an mTLS pair, the private key NEVER leaves the host, only the fingerprint is in the DB).
-- Warrant is SERVICE certs (e.g. Redis server TLS), where the private key
-- is GENERATED by Keeper centrally and passes through Keeper → Vault (R2,
-- a deliberate exception to the identity-model invariant: a service cert is NOT an
-- identity cert, and it already lives in Vault for manual rotate_tls). The private
-- key is NOT stored in the DB - only vault_ref + fingerprint + serial. This decision
-- is recorded in the ADR-017 amendment (cert-rotation Warrant).
--
-- One (incarnation, kind) pair can have many warrant rows (rotation history); exactly
-- one active cert per kind at a time is guaranteed by a partial unique index
-- (symmetric with soul_seeds_active_by_sid_idx).
--
-- FK to incarnation(name) - ON DELETE CASCADE (cert history dies with the
-- incarnation; incarnation.PK = name, TEXT, ADR-009).

CREATE TABLE warrant (
    cert_id                   UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    incarnation_id            TEXT        NOT NULL,
    kind                      TEXT        NOT NULL,
    vault_ref                 TEXT        NOT NULL,
    serial_number             TEXT        NOT NULL,
    fingerprint               TEXT        NOT NULL,
    not_after                 TIMESTAMPTZ NOT NULL,
    issued_at                 TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    pki_mount                 TEXT,
    pki_role                  TEXT,
    status                    TEXT        NOT NULL DEFAULT 'active',
    issued_by_kid             TEXT,
    last_rotation_voyage_id   TEXT,
    auto_rotate               BOOLEAN     NOT NULL DEFAULT true,
    rotate_threshold_override INTERVAL,

    CONSTRAINT warrant_incarnation_fk
        FOREIGN KEY (incarnation_id) REFERENCES incarnation (name) ON DELETE CASCADE,
    CONSTRAINT warrant_kind_valid
        CHECK (kind IN ('cert', 'key', 'ca')),
    CONSTRAINT warrant_status_valid
        CHECK (status IN ('active', 'superseded', 'expired', 'rotating', 'failed')),
    CONSTRAINT warrant_fingerprint_format
        -- SHA-256 hex = 64 lower-hex chars (symmetric with soul_seeds_fingerprint_format).
        CHECK (fingerprint ~ '^[0-9a-f]{64}$')
);

-- Invariant: exactly one active cert per (incarnation, kind) at a time
-- (symmetric with soul_seeds_active_by_sid_idx). Rotation: the old row goes to
-- superseded, the new one to active - both in the same tx, without violating the partial unique.
CREATE UNIQUE INDEX warrant_active_by_incarnation_kind_idx
    ON warrant (incarnation_id, kind)
    WHERE status = 'active';

-- Reaper `rotate_due_certs`: scans expiring active certs by not_after
-- (`not_after < NOW() + threshold`, the effective threshold includes jitter in the predicate).
CREATE INDEX warrant_not_after_idx
    ON warrant (not_after);

-- `purge_old_certs` (R4): retention of superseded/expired rows by age.
CREATE INDEX warrant_status_idx
    ON warrant (status);

COMMENT ON TABLE warrant IS
    'Registry of Warrant - service TLS certs for incarnations (cert-rotation Variant 1, Keeper-centric). One active per (incarnation, kind). The private key is generated by Keeper (R2); only vault_ref+fingerprint+serial live in the DB. Not to be confused with soul_seeds (Soul identity certs, private key never leaves the host).';
