package voyage

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/souls-guild/soul-stack/keeper/internal/pgutil"
)

// PG error codes (parity with errandrun/crud.go).
const (
	pgErrCodeUniqueViolation     = "23505"
	pgErrCodeForeignKeyViolation = "23503"
	pgErrCodeCheckViolation      = "23514"
)

// ExecQueryRower — a narrow subset of pgxpool.Pool needed by the CRUD layer (symmetric
// with errandrun.ExecQueryRower). Unit tests go through a fake, production supplies
// the real pool/Conn/Tx.
type ExecQueryRower interface {
	Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error)
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
	// CopyFrom — batch insert of run units (InsertTargets, S-med-3). pgx.Tx /
	// *pgx.Conn / *pgxpool.Pool implement it natively; the fake in unit tests is a stub.
	CopyFrom(ctx context.Context, tableName pgx.Identifier, columnNames []string, rowSrc pgx.CopyFromSource) (int64, error)
}

// Compile-time check.
var (
	_ ExecQueryRower = (*pgx.Conn)(nil)
	_ ExecQueryRower = (*pgxpool.Pool)(nil)
	_ ExecQueryRower = (pgx.Tx)(nil)
)

// inter_batch_interval is written as a text literal via `$N::interval`, read back as
// float seconds via EXTRACT(EPOCH FROM ...) — pgx doesn't scan a PG interval into
// time.Duration directly, and pulling in pgtype.Interval just for the S4 feature would be premature.
const insertSQL = `
INSERT INTO voyages (
    voyage_id, kind, scenario_name, module, input,
    target_resolved, target_origin,
    batch_size, concurrency, batch_mode, dry_run,
    schedule_at, inter_batch_interval, on_failure,
    total_batches, status, started_by_aid,
    batch_percent, fail_threshold, inter_unit_interval, require_alive,
    cadence_id
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7,
    $8, $9, $10, $11,
    $12, $13::interval, $14,
    $15, $16, $17,
    $18, $19, $20::interval, $21,
    $22
)
RETURNING created_at
`

// Insert inserts a new Voyage with status [StatusPending]. voyage_id (ULID) is
// generated by the caller (API handler S5), the CRUD layer only checks it's non-empty and
// dispatches a UNIQUE violation into [ErrVoyageExists].
//
// Pre-conditions: non-empty VoyageID / StartedByAID; valid Kind; for
// KindScenario — non-empty ScenarioName, for KindCommand — non-empty Module;
// non-empty TargetResolved; OnFailure (if set) is valid; Status is empty or
// StatusPending; BatchSize/Concurrency (if set) > 0. Input is
// serialized by the caller beforehand (empty → CRUD substitutes `{}` itself, parity DEFAULT).
func Insert(ctx context.Context, db ExecQueryRower, v *Voyage) error {
	if v == nil {
		return fmt.Errorf("voyage: nil voyage")
	}
	if v.VoyageID == "" {
		return fmt.Errorf("voyage: empty voyage_id")
	}
	if v.StartedByAID == "" {
		return fmt.Errorf("voyage: empty started_by_aid")
	}
	if !ValidKind(v.Kind) {
		return fmt.Errorf("voyage: invalid kind %q", v.Kind)
	}
	switch v.Kind {
	case KindScenario:
		if v.ScenarioName == nil || *v.ScenarioName == "" {
			return fmt.Errorf("voyage: kind=scenario requires non-empty scenario_name")
		}
		if v.Module != nil && *v.Module != "" {
			return fmt.Errorf("voyage: kind=scenario must not carry module")
		}
	case KindCommand:
		if v.Module == nil || *v.Module == "" {
			return fmt.Errorf("voyage: kind=command requires non-empty module")
		}
		if v.ScenarioName != nil && *v.ScenarioName != "" {
			return fmt.Errorf("voyage: kind=command must not carry scenario_name")
		}
	}
	if len(v.TargetResolved) == 0 {
		return fmt.Errorf("voyage: empty target_resolved")
	}
	if v.BatchSize != nil && *v.BatchSize <= 0 {
		return fmt.Errorf("voyage: batch_size must be > 0, got %d", *v.BatchSize)
	}
	if v.Concurrency != nil && *v.Concurrency <= 0 {
		return fmt.Errorf("voyage: concurrency must be > 0, got %d", *v.Concurrency)
	}
	if v.BatchMode != nil && !ValidBatchMode(*v.BatchMode) {
		return fmt.Errorf("voyage: invalid batch_mode %q", *v.BatchMode)
	}
	if v.BatchPercent != nil && (*v.BatchPercent < 1 || *v.BatchPercent > 100) {
		return fmt.Errorf("voyage: batch_percent must be in [1, 100], got %d", *v.BatchPercent)
	}
	if v.FailThreshold != nil && *v.FailThreshold <= 0 {
		return fmt.Errorf("voyage: fail_threshold must be > 0, got %d", *v.FailThreshold)
	}
	if v.OnFailure != nil && !ValidOnFailure(*v.OnFailure) {
		return fmt.Errorf("voyage: invalid on_failure %q", *v.OnFailure)
	}
	if v.Status == "" {
		// Deferred start (S4): schedule_at in the future → scheduled, otherwise pending.
		// The worker only picks up scheduled once schedule_at <= NOW() (see
		// [ClaimNext]). Comparing UTC wall-clock against local now —
		// ScheduleAt is already normalized to UTC in the insertSQL argument below;
		// comparing against time.Now() is enough to decide the branch.
		if v.ScheduleAt != nil && v.ScheduleAt.After(time.Now()) {
			v.Status = StatusScheduled
		} else {
			v.Status = StatusPending
		}
	}
	if v.Status != StatusPending && v.Status != StatusScheduled {
		return fmt.Errorf("voyage: Insert requires status=pending|scheduled, got %q", v.Status)
	}

	input := v.Input
	if len(input) == 0 {
		input = []byte("{}")
	}

	var scenarioArg, moduleArg, onFailureArg any
	if v.ScenarioName != nil {
		scenarioArg = *v.ScenarioName
	}
	if v.Module != nil {
		moduleArg = *v.Module
	}
	if v.OnFailure != nil {
		onFailureArg = string(*v.OnFailure)
	}
	var originArg any
	if len(v.TargetOrigin) > 0 {
		originArg = []byte(v.TargetOrigin)
	}
	var batchSizeArg, concurrencyArg, batchModeArg any
	if v.BatchSize != nil {
		batchSizeArg = *v.BatchSize
	}
	if v.Concurrency != nil {
		concurrencyArg = *v.Concurrency
	}
	if v.BatchMode != nil {
		batchModeArg = string(*v.BatchMode)
	}
	var scheduleArg any
	if v.ScheduleAt != nil {
		scheduleArg = v.ScheduleAt.UTC()
	}
	var intervalArg any
	if v.InterBatchInterval != nil {
		intervalArg = pgutil.Interval(*v.InterBatchInterval)
	}
	var batchPercentArg, failThresholdArg, interUnitArg, requireAliveArg any
	if v.BatchPercent != nil {
		batchPercentArg = *v.BatchPercent
	}
	if v.FailThreshold != nil {
		failThresholdArg = *v.FailThreshold
	}
	if v.InterUnitInterval != nil {
		interUnitArg = pgutil.Interval(*v.InterUnitInterval)
	}
	if v.RequireAlive != nil {
		requireAliveArg = *v.RequireAlive
	}
	var cadenceIDArg any
	if v.CadenceID != nil {
		cadenceIDArg = *v.CadenceID
	}

	row := db.QueryRow(ctx, insertSQL,
		v.VoyageID,
		string(v.Kind),
		scenarioArg,
		moduleArg,
		input,
		[]byte(v.TargetResolved),
		originArg,
		batchSizeArg,
		concurrencyArg,
		batchModeArg,
		v.DryRun,
		scheduleArg,
		intervalArg,
		onFailureArg,
		v.TotalBatches,
		string(v.Status),
		v.StartedByAID,
		batchPercentArg,
		failThresholdArg,
		interUnitArg,
		requireAliveArg,
		cadenceIDArg,
	)
	if err := row.Scan(&v.CreatedAt); err != nil {
		return mapInsertError(err)
	}
	return nil
}

func mapInsertError(err error) error {
	var pgErr *pgconn.PgError
	if errors.As(err, &pgErr) {
		switch pgErr.Code {
		case pgErrCodeUniqueViolation:
			return fmt.Errorf("%w (constraint %s): %w",
				ErrVoyageExists, pgErr.ConstraintName, err)
		case pgErrCodeForeignKeyViolation:
			return fmt.Errorf("voyage: FK violation on %s: %w", pgErr.ConstraintName, err)
		case pgErrCodeCheckViolation:
			return fmt.Errorf("voyage: CHECK violation on %s: %w", pgErr.ConstraintName, err)
		}
	}
	return fmt.Errorf("voyage: insert: %w", err)
}

const selectColumns = `
    voyage_id, kind, scenario_name, module, input,
    target_resolved, target_origin,
    batch_size, concurrency, batch_mode, dry_run,
    schedule_at, EXTRACT(EPOCH FROM inter_batch_interval)::float8, on_failure,
    total_batches, current_batch_index, status,
    claimed_by_kid, last_renewed_at, claim_expires_at, attempt,
    started_by_aid, created_at, started_at, finished_at, summary,
    batch_percent, fail_threshold, EXTRACT(EPOCH FROM inter_unit_interval)::float8, require_alive,
    cadence_id
`

const selectByIDSQL = `SELECT ` + selectColumns + `
FROM voyages
WHERE voyage_id = $1
`

// SelectByID reads a Voyage by PK. [ErrVoyageNotFound] if absent.
func SelectByID(ctx context.Context, db ExecQueryRower, id string) (*Voyage, error) {
	if id == "" {
		return nil, fmt.Errorf("voyage: empty voyage_id")
	}
	row := db.QueryRow(ctx, selectByIDSQL, id)
	v, err := scanVoyage(row)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrVoyageNotFound
		}
		return nil, fmt.Errorf("voyage: select by id: %w", err)
	}
	return v, nil
}

// scanVoyage — shared scan of a `voyages` row into *Voyage. Used by SelectByID,
// List (via rows.Next), and ClaimNext (RETURNING). Nullable columns are bound via
// pointers; input/target_resolved/target_origin are jsonb bytes;
// inter_batch_interval arrives as float seconds (EXTRACT EPOCH) → time.Duration.
func scanVoyage(row pgx.Row) (*Voyage, error) {
	var (
		v             Voyage
		kindStr       string
		statusStr     string
		scenarioName  *string
		module        *string
		targetOrigin  []byte
		batchSize     *int
		concurrency   *int
		batchModeStr  *string
		scheduleAt    *time.Time
		intervalSecs  *float64
		onFailureStr  *string
		claimedByKID  *string
		lastRenewedAt *time.Time
		claimExpires  *time.Time
		startedAt     *time.Time
		finishedAt    *time.Time
		summaryJSON   []byte
		batchPercent  *int
		failThreshold *int
		interUnitSecs *float64
		requireAlive  *bool
		cadenceID     *string
	)
	if err := row.Scan(
		&v.VoyageID,
		&kindStr,
		&scenarioName,
		&module,
		&v.Input,
		&v.TargetResolved,
		&targetOrigin,
		&batchSize,
		&concurrency,
		&batchModeStr,
		&v.DryRun,
		&scheduleAt,
		&intervalSecs,
		&onFailureStr,
		&v.TotalBatches,
		&v.CurrentBatchIndex,
		&statusStr,
		&claimedByKID,
		&lastRenewedAt,
		&claimExpires,
		&v.Attempt,
		&v.StartedByAID,
		&v.CreatedAt,
		&startedAt,
		&finishedAt,
		&summaryJSON,
		&batchPercent,
		&failThreshold,
		&interUnitSecs,
		&requireAlive,
		&cadenceID,
	); err != nil {
		return nil, err
	}
	v.Kind = Kind(kindStr)
	v.Status = Status(statusStr)
	v.ScenarioName = scenarioName
	v.Module = module
	v.BatchSize = batchSize
	v.Concurrency = concurrency
	if batchModeStr != nil {
		m := BatchMode(*batchModeStr)
		v.BatchMode = &m
	}
	v.ScheduleAt = scheduleAt
	v.ClaimedByKID = claimedByKID
	v.LastRenewedAt = lastRenewedAt
	v.ClaimExpiresAt = claimExpires
	v.StartedAt = startedAt
	v.FinishedAt = finishedAt
	if onFailureStr != nil {
		f := OnFailure(*onFailureStr)
		v.OnFailure = &f
	}
	if intervalSecs != nil {
		d := time.Duration(*intervalSecs * float64(time.Second))
		v.InterBatchInterval = &d
	}
	v.BatchPercent = batchPercent
	v.FailThreshold = failThreshold
	if interUnitSecs != nil {
		d := time.Duration(*interUnitSecs * float64(time.Second))
		v.InterUnitInterval = &d
	}
	v.RequireAlive = requireAlive
	v.CadenceID = cadenceID
	if len(targetOrigin) > 0 {
		v.TargetOrigin = append([]byte(nil), targetOrigin...)
	}
	summary, err := unmarshalSummary(summaryJSON)
	if err != nil {
		return nil, fmt.Errorf("voyage: unmarshal summary: %w", err)
	}
	v.Summary = summary
	return &v, nil
}

// ListFilter — filters for [List] (parity with errandrun.AllFilter). Statuses —
// multi-value OR (empty slice — no filter); Kind — exact (empty string — no
// filter); CreatedAfter (zero-time → no filter) — exclusive lower bound on
// `created_at`; CadenceID — exact (empty string — no filter): child Voyages
// of a single Cadence schedule (`GET /v1/cadences/{id}/runs`, ADR-046 §6).
type ListFilter struct {
	Statuses     []Status
	Kind         Kind
	CreatedAfter time.Time
	CadenceID    string
}

const listSQL = `SELECT ` + selectColumns + `
FROM voyages
WHERE ($1::text[] IS NULL OR cardinality($1::text[]) = 0 OR status = ANY($1::text[]))
  AND ($2::text IS NULL OR kind = $2)
  AND ($3::timestamptz IS NULL OR created_at > $3::timestamptz)
  AND ($6::text IS NULL OR cadence_id = $6)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

const countSQL = `SELECT COUNT(*) FROM voyages
WHERE ($1::text[] IS NULL OR cardinality($1::text[]) = 0 OR status = ANY($1::text[]))
  AND ($2::text IS NULL OR kind = $2)
  AND ($3::timestamptz IS NULL OR created_at > $3::timestamptz)
  AND ($4::text IS NULL OR cadence_id = $4)
`

// List returns a page of Voyages (parity with errandrun.SelectAll): filters by
// status (OR), kind (exact), `created_after` (exclusive), and cadence_id (exact).
// Sorted by `created_at DESC`. Total is the overall row count under the filter
// (a separate COUNT). limit/offset are not validated — the caller has already run them through
// the page parser.
func List(ctx context.Context, db ExecQueryRower, filter ListFilter, offset, limit int) ([]*Voyage, int, error) {
	var statusesArg any
	if len(filter.Statuses) > 0 {
		ss := make([]string, len(filter.Statuses))
		for i, s := range filter.Statuses {
			ss[i] = string(s)
		}
		statusesArg = ss
	}
	var kindArg any
	if filter.Kind != "" {
		kindArg = string(filter.Kind)
	}
	var createdAfterArg any
	if !filter.CreatedAfter.IsZero() {
		createdAfterArg = filter.CreatedAfter.UTC()
	}
	var cadenceIDArg any
	if filter.CadenceID != "" {
		cadenceIDArg = filter.CadenceID
	}

	var total int
	if err := db.QueryRow(ctx, countSQL, statusesArg, kindArg, createdAfterArg, cadenceIDArg).Scan(&total); err != nil {
		return nil, 0, fmt.Errorf("voyage: count: %w", err)
	}

	rows, err := db.Query(ctx, listSQL, statusesArg, kindArg, createdAfterArg, limit, offset, cadenceIDArg)
	if err != nil {
		return nil, 0, fmt.Errorf("voyage: list: %w", err)
	}
	defer rows.Close()

	out := make([]*Voyage, 0, limit)
	for rows.Next() {
		v, scanErr := scanVoyage(rows)
		if scanErr != nil {
			return nil, 0, fmt.Errorf("voyage: list scan: %w", scanErr)
		}
		out = append(out, v)
	}
	if err := rows.Err(); err != nil {
		return nil, 0, fmt.Errorf("voyage: list iter: %w", err)
	}
	return out, total, nil
}

const finalizeWithOwnershipSQL = `
UPDATE voyages
SET status           = $3,
    finished_at      = NOW(),
    summary          = COALESCE($4, summary),
    claimed_by_kid   = NULL,
    claim_expires_at = NULL,
    last_renewed_at  = NULL
WHERE voyage_id      = $1
  AND claimed_by_kid = $2
  AND status         = 'running'
`

// Finalize transitions a running Voyage to a terminal status UNDER the ownership
// CAS guard: the UPDATE only fires when `claimed_by_kid = $kid AND
// status = 'running'`. If the lease was lost between ClaimNext and finalization
// (Reaper reclaim → another Keeper picked it up) — 0 rows → [ErrLeaseLost] (parity
// with errandrun.FinalizeWithOwnership). The caller (VoyageWorker), on getting ErrLeaseLost,
// logs a WARN and does not retry.
//
// finished_at = NOW() (PG-side clock). summary is optional (nil → COALESCE
// keeps the current value). status must be terminal; non-terminal →
// [ErrInvalidStatus].
func Finalize(ctx context.Context, db ExecQueryRower, id, kid string, status Status, summary *Summary) error {
	if id == "" {
		return fmt.Errorf("voyage: empty voyage_id")
	}
	if kid == "" {
		return fmt.Errorf("voyage: empty kid")
	}
	if !ValidStatus(status) {
		return fmt.Errorf("%w: %q", ErrInvalidStatus, status)
	}
	if !IsTerminal(status) {
		return fmt.Errorf("%w: %q is not terminal", ErrInvalidStatus, status)
	}

	summaryJSON, err := marshalSummary(summary)
	if err != nil {
		return fmt.Errorf("voyage: marshal summary: %w", err)
	}
	var summaryArg any
	if summaryJSON != nil {
		summaryArg = summaryJSON
	}

	tag, err := db.Exec(ctx, finalizeWithOwnershipSQL, id, kid, string(status), summaryArg)
	if err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) && pgErr.Code == pgErrCodeCheckViolation {
			return fmt.Errorf("voyage: CHECK violation on %s: %w", pgErr.ConstraintName, err)
		}
		return fmt.Errorf("voyage: finalize: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return ErrLeaseLost
	}
	return nil
}

const verifyOwnershipSQL = `
SELECT 1
FROM voyages
WHERE voyage_id      = $1
  AND claimed_by_kid = $2
  AND attempt        = $3
  AND status         = 'running'
`

// VerifyOwnership — fencing check: "am I still the owner of this Voyage at my attempt".
// Parallel to the [Finalize] CAS predicate (`claimed_by_kid = $kid AND status =
// 'running'`), but with an attempt epoch instead of a write: if the Voyage was reclaimed by another
// Keeper (Reaper returned it to pending → ClaimNext incremented attempt → a new
// owner), the row won't match — [ErrLeaseLost]. attempt distinguishes "our own claim"
// from a re-claim by the same KID after a reclaim (ADR-027(g) fencing epoch).
//
// Called before a side effect that does NOT have its own ownership guard
// (command-leg-spawn dispatches an Errand before the MarkTargetRunning CAS; without fencing —
// a duplicate Errand on reclaim mid-Leg, S-med-2). nil — owner;
// [ErrLeaseLost] — lease lost; any other error — a PG CRUD failure.
func VerifyOwnership(ctx context.Context, db ExecQueryRower, id, kid string, attempt int) error {
	if id == "" {
		return fmt.Errorf("voyage: empty voyage_id")
	}
	if kid == "" {
		return fmt.Errorf("voyage: empty kid")
	}
	var one int
	err := db.QueryRow(ctx, verifyOwnershipSQL, id, kid, attempt).Scan(&one)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return ErrLeaseLost
		}
		return fmt.Errorf("voyage: verify ownership: %w", err)
	}
	return nil
}
