package voyage

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/souls-guild/soul-stack/keeper/internal/pgutil"
)

// PG error codes (parity with errandrun/crud.go).
const (
	pgErrCodeUniqueViolation     = "23505"
	pgErrCodeForeignKeyViolation = "23503"
	pgErrCodeCheckViolation      = "23514"
)

// ExecQueryRower — a narrow subset of pgxpool.Pool needed by the CRUD layer (symmetric
// with errandrun.ExecQueryRower). Unit tests go through a fake, production supplies
// the real pool/Conn/Tx.
type ExecQueryRower interface {
	Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error)
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
	// CopyFrom — batch insert of run units (InsertTargets, S-med-3). pgx.Tx /
	// *pgx.Conn / *pgxpool.Pool implement it natively; the fake in unit tests is a stub.
	CopyFrom(ctx context.Context, tableName pgx.Identifier, columnNames []string, rowSrc pgx.CopyFromSource) (int64, error)
}

// Compile-time check.
var (
	_ ExecQueryRower = (*pgx.Conn)(nil)
	_ ExecQueryRower = (*pgxpool.Pool)(nil)
	_ ExecQueryRower = (pgx.Tx)(nil)
)

// inter_batch_interval is written as a text literal via `$N::interval`, read back as
// float seconds via EXTRACT(EPOCH FROM ...) — pgx doesn't scan a PG interval into
// time.Duration directly, and pulling in pgtype.Interval just for the S4 feature would be premature.
const insertSQL = `
INSERT INTO voyages (
    voyage_id, kind, scenario_name, module, input,
    target_resolved, target_origin,
    batch_size, concurrency, batch_mode, dry_run,
    schedule_at, inter_batch_interval, on_failure,
    total_batches, status, started_by_aid,
    batch_percent, fail_threshold, inter_unit_interval, require_alive,
    cadence_id
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7,
    $8, $9, $10, $11,
    $12, $13::interval, $14,
    $15, $16, $17,
    $18, $19, $20::interval, $21,
    $22
)
RETURNING created_at
`

// Insert inserts a new Voyage with status [StatusPending]. voyage_id (ULID) is
// generated by the caller (API handler S5), the CRUD layer only checks it's non-empty and
// dispatches a UNIQUE violation into [ErrVoyageExists].
//
// Pre-conditions: non-empty VoyageID / StartedByAID; valid Kind; for
// KindScenario — non-empty ScenarioName, for KindCommand — non-empty Module;
// non-empty TargetResolved; OnFailure (if set) is valid; Status is empty or
// StatusPending; BatchSize/Concurrency (if set) > 0. Input is
// serialized by the caller beforehand (empty → CRUD substitutes `{}` itself, parity DEFAULT).
func Insert(ctx context.Context, db ExecQueryRower, v *Voyage) error {
	if v == nil {
		return fmt.Errorf("voyage: nil voyage")
	}
	if v.VoyageID == "" {
		return fmt.Errorf("voyage: empty voyage_id")
	}
	if v.StartedByAID == "" {
		return fmt.Errorf("voyage: empty started_by_aid")
	}
	if !ValidKind(v.Kind) {
		return fmt.Errorf("voyage: invalid kind %q", v.Kind)
	}
	switch v.Kind {
	case KindScenario:
		if v.ScenarioName == nil || *v.ScenarioName == "" {
			return fmt.Errorf("voyage: kind=scenario requires non-empty scenario_name")
		}
		if v.Module != nil && *v.Module != "" {
			return fmt.Errorf("voyage: kind=scenario must not carry module")
		}
	case KindCommand:
		if v.Module == nil || *v.Module == "" {
			return fmt.Errorf("voyage: kind=command requires non-empty module")
		}
		if v.ScenarioName != nil && *v.ScenarioName != "" {
			return fmt.Errorf("voyage: kind=command must not carry scenario_name")
		}
	}
	if len(v.TargetResolved) == 0 {
		return fmt.Errorf("voyage: empty target_resolved")
	}
	if v.BatchSize != nil && *v.BatchSize <= 0 {
		return fmt.Errorf("voyage: batch_size must be > 0, got %d", *v.BatchSize)
	}
	if v.Concurrency != nil && *v.Concurrency <= 0 {
		return fmt.Errorf("voyage: concurrency must be > 0, got %d", *v.Concurrency)
	}
	if v.BatchMode != nil && !ValidBatchMode(*v.BatchMode) {
		return fmt.Errorf("voyage: invalid batch_mode %q", *v.BatchMode)
	}
	if v.BatchPercent != nil && (*v.BatchPercent < 1 || *v.BatchPercent > 100) {
		return fmt.Errorf("voyage: batch_percent must be in [1, 100], got %d", *v.BatchPercent)
	}
	if v.FailThreshold != nil && *v.FailThreshold <= 0 {
		return fmt.Errorf("voyage: fail_threshold must be > 0, got %d", *v.FailThreshold)
	}
	if v.OnFailure != nil && !ValidOnFailure(*v.OnFailure) {
		return fmt.Errorf("voyage: invalid on_failure %q", *v.OnFailure)
	}
	if v.Status == "" {
		// Deferred start (S4): schedule_at in the future → scheduled, otherwise pending.
		// The worker only picks up scheduled once schedule_at <= NOW() (see
		// [ClaimNext]). Comparing UTC wall-clock against local now —
		// ScheduleAt is already normalized to UTC in the insertSQL argument below;
		// comparing against time.Now() is enough to decide the branch.
		if v.ScheduleAt != nil && v.ScheduleAt.After(time.Now()) {
			v.Status = StatusScheduled
		} else {
			v.Status = StatusPending
		}
	}
	if v.Status != StatusPending && v.Status != StatusScheduled {
		return fmt.Errorf("voyage: Insert requires status=pending|scheduled, got %q", v.Status)
	}

	input := v.Input
	if len(input) == 0 {
		input = []byte("{}")
	}

	var scenarioArg, moduleArg, onFailureArg any
	if v.ScenarioName != nil {
		scenarioArg = *v.ScenarioName
	}
	if v.Module != nil {
		moduleArg = *v.Module
	}
	if v.OnFailure != nil {
		onFailureArg = string(*v.OnFailure)
	}
	var originArg any
	if len(v.TargetOrigin) > 0 {
		originArg = []byte(v.TargetOrigin)
	}
	var batchSizeArg, concurrencyArg, batchModeArg any
	if v.BatchSize != nil {
		batchSizeArg = *v.BatchSize
	}
	if v.Concurrency != nil {
		concurrencyArg = *v.Concurrency
	}
	if v.BatchMode != nil {
		batchModeArg = string(*v.BatchMode)
	}
	var scheduleArg any
	if v.ScheduleAt != nil {
		scheduleArg = v.ScheduleAt.UTC()
	}
	var intervalArg any
	if v.InterBatchInterval != nil {
		intervalArg = pgutil.Interval(*v.InterBatchInterval)
	}
	var batchPercentArg, failThresholdArg, interUnitArg, requireAliveArg any
	if v.BatchPercent != nil {
		batchPercentArg = *v.BatchPercent
	}
	if v.FailThreshold != nil {
		failThresholdArg = *v.FailThreshold
	}
	if v.InterUnitInterval != nil {
		interUnitArg = pgutil.Interval(*v.InterUnitInterval)
	}
	if v.RequireAlive != nil {
		requireAliveArg = *v.RequireAlive
	}
	var cadenceIDArg any
	if v.CadenceID != nil {
		cadenceIDArg = *v.CadenceID
	}

	row := db.QueryRow(ctx, insertSQL,
		v.VoyageID,
		string(v.Kind),
		scenarioArg,
		moduleArg,
		input,
		[]byte(v.TargetResolved),
		originArg,
		batchSizeArg,
		concurrencyArg,
		batchModeArg,
		v.DryRun,
		scheduleArg,
		intervalArg,
		onFailureArg,
		v.TotalBatches,
		string(v.Status),
		v.StartedByAID,
		batchPercentArg,
		failThresholdArg,
		interUnitArg,
		requireAliveArg,
		cadenceIDArg,
	)
	if err := row.Scan(&v.CreatedAt); err != nil {
		return mapInsertError(err)
	}
	return nil
}

func mapInsertError(err error) error {
	var pgErr *pgconn.PgError
	if errors.As(err, &pgErr) {
		switch pgErr.Code {
		case pgErrCodeUniqueViolation:
			return fmt.Errorf("%w (constraint %s): %w",
				ErrVoyageExists, pgErr.ConstraintName, err)
		case pgErrCodeForeignKeyViolation:
			return fmt.Errorf("voyage: FK violation on %s: %w", pgErr.ConstraintName, err)
		case pgErrCodeCheckViolation:
			return fmt.Errorf("voyage: CHECK violation on %s: %w", pgErr.ConstraintName, err)
		}
	}
	return fmt.Errorf("voyage: insert: %w", err)
}

const selectColumns = `
    voyage_id, kind, scenario_name, module, input,
    target_resolved, target_origin,
    batch_size, concurrency, batch_mode, dry_run,
    schedule_at, EXTRACT(EPOCH FROM inter_batch_interval)::float8, on_failure,
    total_batches, current_batch_index, status,
    claimed_by_kid, last_renewed_at, claim_expires_at, attempt,
    started_by_aid, created_at, started_at, finished_at, summary,
    batch_percent, fail_threshold, EXTRACT(EPOCH FROM inter_unit_interval)::float8, require_alive,
    cadence_id
`

const selectByIDSQL = `SELECT ` + selectColumns + `
FROM voyages
WHERE voyage_id = $1
`

// SelectByID reads a Voyage by PK. [ErrVoyageNotFound] if absent.
//
// Unnarrowed: the orchestration paths (claim, finalize, cancel) must see every
// Voyage regardless of who is asking. An operator READ goes through
// [SelectByIDScoped] instead.
func SelectByID(ctx context.Context, db ExecQueryRower, id string) (*Voyage, error) {
	return SelectByIDScoped(ctx, db, id, nil)
}

// SelectByIDScoped reads a Voyage by PK, narrowed to the caller's host boundary
// (NIM-842). hostScope is the per-target predicate, wrapped by [HostScopeSQL];
// nil applies no narrowing.
//
// A Voyage outside the boundary is [ErrVoyageNotFound] — the SAME answer an
// absent id gets, and the reason the narrowing lives in the WHERE rather than in
// a check on the scanned row. A distinct refusal would confirm the run exists,
// which is the disclosure this is closing, only one id at a time.
func SelectByIDScoped(ctx context.Context, db ExecQueryRower, id string, hostScope func(startIdx int) (string, []any, int)) (*Voyage, error) {
	if id == "" {
		return nil, fmt.Errorf("voyage: empty voyage_id")
	}
	sql, args := selectByIDSQL, []any{id}
	if hostScope != nil {
		pred, scopeArgs, _ := hostScope(len(args) + 1)
		sql += "  AND " + pred + "\n"
		args = append(args, scopeArgs...)
	}
	row := db.QueryRow(ctx, sql, args...)
	v, err := scanVoyage(row)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrVoyageNotFound
		}
		return nil, fmt.Errorf("voyage: select by id: %w", err)
	}
	return v, nil
}

// scanVoyage — shared scan of a `voyages` row into *Voyage. Used by SelectByID,
// List (via rows.Next), and ClaimNext (RETURNING). Nullable columns are bound via
// pointers; input/target_resolved/target_origin are jsonb bytes;
// inter_batch_interval arrives as float seconds (EXTRACT EPOCH) → time.Duration.
func scanVoyage(row pgx.Row) (*Voyage, error) {
	var (
		v             Voyage
		kindStr       string
		statusStr     string
		scenarioName  *string
		module        *string
		targetOrigin  []byte
		batchSize     *int
		concurrency   *int
		batchModeStr  *string
		scheduleAt    *time.Time
		intervalSecs  *float64
		onFailureStr  *string
		claimedByKID  *string
		lastRenewedAt *time.Time
		claimExpires  *time.Time
		startedAt     *time.Time
		finishedAt    *time.Time
		summaryJSON   []byte
		batchPercent  *int
		failThreshold *int
		interUnitSecs *float64
		requireAlive  *bool
		cadenceID     *string
	)
	if err := row.Scan(
		&v.VoyageID,
		&kindStr,
		&scenarioName,
		&module,
		&v.Input,
		&v.TargetResolved,
		&targetOrigin,
		&batchSize,
		&concurrency,
		&batchModeStr,
		&v.DryRun,
		&scheduleAt,
		&intervalSecs,
		&onFailureStr,
		&v.TotalBatches,
		&v.CurrentBatchIndex,
		&statusStr,
		&claimedByKID,
		&lastRenewedAt,
		&claimExpires,
		&v.Attempt,
		&v.StartedByAID,
		&v.CreatedAt,
		&startedAt,
		&finishedAt,
		&summaryJSON,
		&batchPercent,
		&failThreshold,
		&interUnitSecs,
		&requireAlive,
		&cadenceID,
	); err != nil {
		return nil, err
	}
	v.Kind = Kind(kindStr)
	v.Status = Status(statusStr)
	v.ScenarioName = scenarioName
	v.Module = module
	v.BatchSize = batchSize
	v.Concurrency = concurrency
	if batchModeStr != nil {
		m := BatchMode(*batchModeStr)
		v.BatchMode = &m
	}
	v.ScheduleAt = scheduleAt
	v.ClaimedByKID = claimedByKID
	v.LastRenewedAt = lastRenewedAt
	v.ClaimExpiresAt = claimExpires
	v.StartedAt = startedAt
	v.FinishedAt = finishedAt
	if onFailureStr != nil {
		f := OnFailure(*onFailureStr)
		v.OnFailure = &f
	}
	if intervalSecs != nil {
		d := time.Duration(*intervalSecs * float64(time.Second))
		v.InterBatchInterval = &d
	}
	v.BatchPercent = batchPercent
	v.FailThreshold = failThreshold
	if interUnitSecs != nil {
		d := time.Duration(*interUnitSecs * float64(time.Second))
		v.InterUnitInterval = &d
	}
	v.RequireAlive = requireAlive
	v.CadenceID = cadenceID
	if len(targetOrigin) > 0 {
		v.TargetOrigin = append([]byte(nil), targetOrigin...)
	}
	summary, err := unmarshalSummary(summaryJSON)
	if err != nil {
		return nil, fmt.Errorf("voyage: unmarshal summary: %w", err)
	}
	v.Summary = summary
	return &v, nil
}

// ListFilter — filters for [List] (parity with errandrun.AllFilter). Statuses —
// multi-value OR (empty slice — no filter); Kind — exact (empty string — no
// filter); CreatedAfter (zero-time → no filter) — exclusive lower bound on
// `created_at`; CadenceID — exact (empty string — no filter): child Voyages
// of a single Cadence schedule (`GET /v1/cadences/{id}/runs`, ADR-046 §6).
type ListFilter struct {
	Statuses     []Status
	Kind         Kind
	CreatedAfter time.Time
	CadenceID    string

	// HostScope renders the caller's purview over the hosts a Voyage NAMES,
	// starting at placeholder $startIdx (NIM-842). Supply the per-target
	// predicate; [HostScopeSQL] wraps it. A nil HostScope applies NO narrowing
	// and must therefore only ever be passed by a caller that has already
	// established the operator may see every host.
	//
	// It is pushed into the query rather than applied to the rows that come
	// back because `total` is counted under the same WHERE: a Go post-filter
	// would hide the runs and still publish how many of them there are.
	HostScope func(startIdx int) (string, []any, int)
}

// The column aliases a per-target predicate must be written against inside
// [HostScopeSQL]'s subquery. Exported so the RBAC-side mapping is built from
// these rather than from a second copy of the same strings — a predicate naming
// a column the subquery does not have is a runtime SQL error on a security path.
//
// [ScopeHostColumn] is the SID the Voyage RECORDED, not the joined one, so a run
// against a host since removed from the registry stays reachable by an operator
// scoped to that host. Coven and traits come from the join and go NULL with the
// host, which the `IS NOT TRUE` in [HostScopeSQL] reads as out-of-scope.
const (
	ScopeHostColumn   = "_t.sid"
	ScopeCovenColumn  = "_s.coven"
	ScopeTraitsColumn = "_s.traits"
)

// HostScopeSQL renders "every host this Voyage names is inside the operator's
// boundary", wrapping the per-target predicate inner produces (NIM-842).
//
// Only a kind=command Voyage names hosts: its `target_resolved` is a JSON array
// of SIDs and its per-target rows carry them as `target_id`. A kind=scenario
// Voyage names incarnations, which `incarnation.history` — the right already
// gating these routes — is the correct control for, so it is left alone rather
// than narrowed by a host permission that says nothing about it.
//
// ALL, not ANY: a run is shown only when every host it touched is visible. The
// alternative would hand back a target list mixing hosts the caller may see with
// hosts they may not, and the identities of the second kind are the disclosure.
//
// `IS NOT TRUE`, not `NOT`: the coven predicate is an array overlap, and a host
// missing from `souls` makes it NULL rather than false. Under plain `NOT` that
// NULL would drop the target from the subquery and count as in-scope — open in
// exactly the case where least is known.
//
// The three purview arms fall out of inner without a branch here: Unrestricted
// renders TRUE, so no target is ever out of scope; an empty purview renders
// FALSE, so every target is. The one gap is a command Voyage that resolved to NO
// hosts — it has no target to fail the test, so it stays visible, carrying its
// declared `target_origin`. It names no host that exists, which is why this is
// left rather than closed with a length guard that would also hide it from an
// unrestricted operator.
// The `jsonb_typeof = 'array'` arm is availability, not scope:
// `jsonb_array_elements_text` RAISES on a scalar rather than returning no rows,
// so a single malformed `target_resolved` would 500 the whole list for every
// caller, cluster-admin included. Nothing writes one today — the create paths
// refuse an empty target with 422 — but this predicate is the first thing to
// read that column's SHAPE, so it carries its own guard. It is a CASE and not an
// AND because AND has no evaluation order in Postgres and the point is to not
// reach the function. A non-array falls to FALSE: hidden, like any target that
// cannot be shown to be in scope.
func HostScopeSQL(inner func(startIdx int) (string, []any, int), startIdx int) (string, []any, int) {
	pred, args, next := inner(startIdx)
	return `(voyages.kind <> 'command' OR CASE
        WHEN jsonb_typeof(voyages.target_resolved) <> 'array' THEN FALSE
        ELSE NOT EXISTS (
            SELECT 1 FROM jsonb_array_elements_text(voyages.target_resolved) AS _t(sid)
            LEFT JOIN souls _s ON _s.sid = _t.sid
            WHERE (` + pred + `) IS NOT TRUE)
        END)`, args, next
}

const listSQL = `SELECT ` + selectColumns + `
FROM voyages
WHERE ($1::text[] IS NULL OR cardinality($1::text[]) = 0 OR status = ANY($1::text[]))
  AND ($2::text IS NULL OR kind = $2)
  AND ($3::timestamptz IS NULL OR created_at > $3::timestamptz)
  AND ($6::text IS NULL OR cadence_id = $6)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

const countSQL = `SELECT COUNT(*) FROM voyages
WHERE ($1::text[] IS NULL OR cardinality($1::text[]) = 0 OR status = ANY($1::text[]))
  AND ($2::text IS NULL OR kind = $2)
  AND ($3::timestamptz IS NULL OR created_at > $3::timestamptz)
  AND ($4::text IS NULL OR cadence_id = $4)
`

// List returns a page of Voyages (parity with errandrun.SelectAll): filters by
// status (OR), kind (exact), `created_after` (exclusive), and cadence_id (exact).
// Sorted by `created_at DESC`. Total is the overall row count under the filter
// (a separate COUNT). limit/offset are not validated — the caller has already run them through
// the page parser.
func List(ctx context.Context, db ExecQueryRower, filter ListFilter, offset, limit int) ([]*Voyage, int, error) {
	var statusesArg any
	if len(filter.Statuses) > 0 {
		ss := make([]string, len(filter.Statuses))
		for i, s := range filter.Statuses {
			ss[i] = string(s)
		}
		statusesArg = ss
	}
	var kindArg any
	if filter.Kind != "" {
		kindArg = string(filter.Kind)
	}
	var createdAfterArg any
	if !filter.CreatedAfter.IsZero() {
		createdAfterArg = filter.CreatedAfter.UTC()
	}
	var cadenceIDArg any
	if filter.CadenceID != "" {
		cadenceIDArg = filter.CadenceID
	}

	// The scope predicate is ANDed LAST, after every user-supplied filter, so no
	// filter can widen it. Its placeholders start after the fixed ones, which
	// differ between the two statements ($1..$4 for the count, $1..$6 for the
	// page), so each is rendered against its own starting index.
	countArgs := []any{statusesArg, kindArg, createdAfterArg, cadenceIDArg}
	countStmt := countSQL
	listArgs := []any{statusesArg, kindArg, createdAfterArg, limit, offset, cadenceIDArg}
	listStmt := listSQL
	if filter.HostScope != nil {
		sql, args, _ := filter.HostScope(len(countArgs) + 1)
		countStmt += "  AND " + sql + "\n"
		countArgs = append(countArgs, args...)

		sql, args, _ = filter.HostScope(len(listArgs) + 1)
		// spliceBefore, not strings.Replace: Replace returns the input unchanged
		// when the needle is absent, while the args are appended either way — so
		// rewording the ORDER BY would give the page N+1 bindings for N
		// placeholders and a runtime 500, with nothing at review time to see.
		listStmt = spliceBefore(listStmt, "ORDER BY created_at DESC", "  AND "+sql+"\n")
		listArgs = append(listArgs, args...)
	}

	var total int
	if err := db.QueryRow(ctx, countStmt, countArgs...).Scan(&total); err != nil {
		return nil, 0, fmt.Errorf("voyage: count: %w", err)
	}

	rows, err := db.Query(ctx, listStmt, listArgs...)
	if err != nil {
		return nil, 0, fmt.Errorf("voyage: list: %w", err)
	}
	defer rows.Close()

	out := make([]*Voyage, 0, limit)
	for rows.Next() {
		v, scanErr := scanVoyage(rows)
		if scanErr != nil {
			return nil, 0, fmt.Errorf("voyage: list scan: %w", scanErr)
		}
		out = append(out, v)
	}
	if err := rows.Err(); err != nil {
		return nil, 0, fmt.Errorf("voyage: list iter: %w", err)
	}
	return out, total, nil
}

const finalizeWithOwnershipSQL = `
UPDATE voyages
SET status           = $3,
    finished_at      = NOW(),
    summary          = COALESCE($4, summary),
    claimed_by_kid   = NULL,
    claim_expires_at = NULL,
    last_renewed_at  = NULL
WHERE voyage_id      = $1
  AND claimed_by_kid = $2
  AND status         = 'running'
`

// Finalize transitions a running Voyage to a terminal status UNDER the ownership
// CAS guard: the UPDATE only fires when `claimed_by_kid = $kid AND
// status = 'running'`. If the lease was lost between ClaimNext and finalization
// (Reaper reclaim → another Keeper picked it up) — 0 rows → [ErrLeaseLost] (parity
// with errandrun.FinalizeWithOwnership). The caller (VoyageWorker), on getting ErrLeaseLost,
// logs a WARN and does not retry.
//
// finished_at = NOW() (PG-side clock). summary is optional (nil → COALESCE
// keeps the current value). status must be terminal; non-terminal →
// [ErrInvalidStatus].
func Finalize(ctx context.Context, db ExecQueryRower, id, kid string, status Status, summary *Summary) error {
	if id == "" {
		return fmt.Errorf("voyage: empty voyage_id")
	}
	if kid == "" {
		return fmt.Errorf("voyage: empty kid")
	}
	if !ValidStatus(status) {
		return fmt.Errorf("%w: %q", ErrInvalidStatus, status)
	}
	if !IsTerminal(status) {
		return fmt.Errorf("%w: %q is not terminal", ErrInvalidStatus, status)
	}

	summaryJSON, err := marshalSummary(summary)
	if err != nil {
		return fmt.Errorf("voyage: marshal summary: %w", err)
	}
	var summaryArg any
	if summaryJSON != nil {
		summaryArg = summaryJSON
	}

	tag, err := db.Exec(ctx, finalizeWithOwnershipSQL, id, kid, string(status), summaryArg)
	if err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) && pgErr.Code == pgErrCodeCheckViolation {
			return fmt.Errorf("voyage: CHECK violation on %s: %w", pgErr.ConstraintName, err)
		}
		return fmt.Errorf("voyage: finalize: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return ErrLeaseLost
	}
	return nil
}

const verifyOwnershipSQL = `
SELECT 1
FROM voyages
WHERE voyage_id      = $1
  AND claimed_by_kid = $2
  AND attempt        = $3
  AND status         = 'running'
`

// VerifyOwnership — fencing check: "am I still the owner of this Voyage at my attempt".
// Parallel to the [Finalize] CAS predicate (`claimed_by_kid = $kid AND status =
// 'running'`), but with an attempt epoch instead of a write: if the Voyage was reclaimed by another
// Keeper (Reaper returned it to pending → ClaimNext incremented attempt → a new
// owner), the row won't match — [ErrLeaseLost]. attempt distinguishes "our own claim"
// from a re-claim by the same KID after a reclaim (ADR-027(g) fencing epoch).
//
// Called before a side effect that does NOT have its own ownership guard
// (command-leg-spawn dispatches an Errand before the MarkTargetRunning CAS; without fencing —
// a duplicate Errand on reclaim mid-Leg, S-med-2). nil — owner;
// [ErrLeaseLost] — lease lost; any other error — a PG CRUD failure.
func VerifyOwnership(ctx context.Context, db ExecQueryRower, id, kid string, attempt int) error {
	if id == "" {
		return fmt.Errorf("voyage: empty voyage_id")
	}
	if kid == "" {
		return fmt.Errorf("voyage: empty kid")
	}
	var one int
	err := db.QueryRow(ctx, verifyOwnershipSQL, id, kid, attempt).Scan(&one)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return ErrLeaseLost
		}
		return fmt.Errorf("voyage: verify ownership: %w", err)
	}
	return nil
}

// spliceBefore inserts ins immediately before the first occurrence of anchor,
// and PANICS when the anchor is absent. A panic on a constant this package owns
// is a programming error surfaced at the first test that runs the query — the
// alternative is a statement whose bindings and placeholders have silently
// stopped matching, which fails as a 500 on a security path in production.
func spliceBefore(stmt, anchor, ins string) string {
	i := strings.Index(stmt, anchor)
	if i < 0 {
		panic("voyage: scope splice anchor not found in statement: " + anchor)
	}
	return stmt[:i] + ins + stmt[i:]
}
