# Makefile for the {{.BinaryName}} plugin (SoulModule {{.Namespace}}.{{.Name}}).

BIN_DIR := bin
BINARY  := $(BIN_DIR)/{{.BinaryName}}

.PHONY: build test fmt vet check

build:
	@mkdir -p $(BIN_DIR)
	@go build -o $(BINARY) ./cmd/{{.BinaryName}}

test:
	@go test ./...

fmt:
	@gofmt -w .

vet:
	@go vet ./...

check: fmt vet test build
	@echo "check: $(BINARY) ok"
