package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"

	pluginv1 "github.com/souls-guild/soul-stack/proto/plugin/gen/go/v1"
	"github.com/souls-guild/soul-stack/sdk/sshprovider"
)

// paramsEnv is the env var through which keeper.push passes params (JSON per
// schema.json) to the teleport provider when the plugin is forked. Symmetrical
// with soul-ssh-vault / soul-ssh-static: the SshProvider contract
// (Sign/Authorize) carries no per-request provider params, so config arrives at
// process startup, just like the socket path.
const paramsEnv = "SOUL_SSH_TELEPORT_PARAMS"

// params is the teleport-provider configuration parsed from paramsEnv.
type params struct {
	// ProxyAddr is the Teleport-proxy endpoint (`host:port`). It goes into
	// SignReply.proxy_jump for later keeper.push use (dispatcher proxy_jump
	// support - S3).
	ProxyAddr string `json:"proxy_addr"`
	// ClusterName is the Teleport cluster name (optional, for multi-cluster trust).
	ClusterName string `json:"cluster_name"`
	// IdentityFile is the path to the Teleport identity-file (creds-flow B).
	IdentityFile string `json:"identity_file"`
	// TbotSocket is the path to the Unix socket of the tbot daemon (alternative to
	// IdentityFile). One of the two sources is required.
	TbotSocket string `json:"tbot_socket"`
	// Roles is the list of Teleport roles under which the cert is requested.
	// Empty = default identity/bot roles.
	Roles []string `json:"roles"`
	// ValidPrincipals is a principal allowlist over the Teleport role; empty =
	// accept any req.User.
	ValidPrincipals []string `json:"valid_principals"`
	// Deny is the deny-list of (host, user) pairs; empty = allow-all (dev/test).
	Deny []denyRule `json:"deny"`
}

// denyRule is one deny-list entry. An empty field is a wildcard for that
// dimension. Semantics match soul-ssh-vault / soul-ssh-static.
type denyRule struct {
	Host string `json:"host"`
	User string `json:"user"`
}

func (r denyRule) matches(host, user string) bool {
	return (r.Host == "" || r.Host == host) && (r.User == "" || r.User == user)
}

// loadParams reads and validates params from env. Fail-closed: invalid JSON,
// missing proxy_addr, or missing credentials source (both identity_file and
// tbot_socket empty) returns an error and the plugin does not start.
func loadParams() (params, error) {
	raw := os.Getenv(paramsEnv)
	if raw == "" {
		return params{}, fmt.Errorf("env %s is empty: teleport provider requires params", paramsEnv)
	}
	var p params
	if err := json.Unmarshal([]byte(raw), &p); err != nil {
		return params{}, fmt.Errorf("parse %s: %w", paramsEnv, err)
	}
	if p.ProxyAddr == "" {
		return params{}, errors.New("proxy_addr is required (Teleport proxy host:port)")
	}
	if p.IdentityFile == "" && p.TbotSocket == "" {
		return params{}, errors.New("credentials source required: identity_file or tbot_socket")
	}
	if p.IdentityFile != "" && p.TbotSocket != "" {
		return params{}, errors.New("identity_file and tbot_socket are mutually exclusive (oneOf)")
	}
	return p, nil
}

// TeleportProvider is an SshProvider over the Teleport Auth API.
//
// Sign: authenticates to Teleport through identity_file/tbot, calls
// GenerateUserCerts on req.PublicKey (Keeper-ephemeral), returns only
// certificate (private_key="") + proxy_jump=<proxy_addr>. Authorize: deny-list,
// defaults to allow-all.
type TeleportProvider struct {
	sshprovider.BaseProvider
	cfg params
	// newClient is the Teleport-client factory (injected for unit tests).
	// nil -> defaultClient.
	newClient func(ctx context.Context, p params) (teleportClient, error)
}

// teleportClient is a narrow interface over Teleport Auth API: only what
// TeleportProvider uses. It keeps unit tests simple (mock without the full SDK)
// and narrows the dependency surface - production implementation lives in one
// place.
type teleportClient interface {
	// GenerateUserSSHCert calls Teleport `GenerateUserCerts` with the given
	// public_key and principal. It returns PEM/openssh-encoded SSH user
	// certificate (Cert field of the SSH response). It does not return private_key
	// - Keeper-ephemeral mode keeps the private key with Keeper.
	GenerateUserSSHCert(ctx context.Context, pubkey, principal string, roles []string) (cert string, err error)
	// Close releases the gRPC connection to Teleport (best-effort).
	Close() error
}

// Sign is Keeper-ephemeral mode (PM-decision SSH key-ownership):
//
//   - req.PublicKey must be a non-empty OpenSSH authorized_keys-encoded pubkey
//     (ephemeral key generated by Keeper per session). Empty -> fail-closed
//     (Teleport CA does not sign an "empty" key).
//   - principal is req.User (Linux user on the push host); if valid_principals is
//     set in params, req.User must be included (local allowlist over the Teleport
//     role).
//   - reply.private_key = "" - the private key stays with Keeper.
//   - reply.proxy_jump = cfg.ProxyAddr - for later keeper.push use (during the
//     pilot, dispatcher ignores this field; see the package docstring and
//     docs/keeper/plugins.md).
func (t *TeleportProvider) Sign(ctx context.Context, req *pluginv1.SignRequest) (*pluginv1.SignReply, error) {
	if req.GetPublicKey() == "" {
		return nil, sshprovider.SignError(sshprovider.SignFailIssue,
			errors.New("public_key is empty: Teleport works only in Keeper-ephemeral mode"))
	}
	if len(t.cfg.ValidPrincipals) > 0 && !contains(t.cfg.ValidPrincipals, req.GetUser()) {
		return nil, sshprovider.SignError(sshprovider.SignFailIssue,
			fmt.Errorf("user %q is not in valid_principals", req.GetUser()))
	}

	newClient := t.newClient
	if newClient == nil {
		newClient = defaultClient
	}
	client, err := newClient(ctx, t.cfg)
	if err != nil {
		return nil, sshprovider.SignError(sshprovider.SignFailIssue,
			fmt.Errorf("teleport auth: %w", err))
	}
	defer func() { _ = client.Close() }()

	signed, err := client.GenerateUserSSHCert(ctx, req.GetPublicKey(), req.GetUser(), t.cfg.Roles)
	if err != nil {
		return nil, sshprovider.SignError(sshprovider.SignFailIssue,
			fmt.Errorf("teleport GenerateUserCerts: %w", err))
	}
	if signed == "" {
		return nil, sshprovider.SignError(sshprovider.SignFailIssue,
			errors.New("teleport returned empty ssh-cert"))
	}

	return &pluginv1.SignReply{
		Certificate: signed,
		PrivateKey:  "",
		// Teleport-cert TTL comes from the Auth role; keeper.push currently does
		// not schedule refresh (one-shot cert per session), 0 = "no refresh".
		TtlSeconds: 0,
		ProxyJump:  t.cfg.ProxyAddr,
	}, nil
}

// Authorize applies the deny-list. Empty deny -> allow-all (dev/test).
// Symmetrical with soul-ssh-vault / soul-ssh-static: the SshProvider rollout
// uses the shared reason-code dictionary from sdk/sshprovider to aggregate
// denial reasons in Keeper audit.
func (t *TeleportProvider) Authorize(_ context.Context, req *pluginv1.AuthorizeRequest) (*pluginv1.AuthorizeReply, error) {
	for _, rule := range t.cfg.Deny {
		if rule.matches(req.GetHost(), req.GetUser()) {
			return &pluginv1.AuthorizeReply{
				Allowed: false,
				Reason:  sshprovider.DenyMessage(sshprovider.DenyExplicitDeny, req.GetUser()+"@"+req.GetHost()),
			}, nil
		}
	}
	return &pluginv1.AuthorizeReply{Allowed: true}, nil
}

func contains(xs []string, x string) bool {
	for _, v := range xs {
		if v == x {
			return true
		}
	}
	return false
}
