package vault

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
)

// serviceCSRKeySize is RSA key size for service cert. 2048 matches SoulSeed-CSR
// (soul/internal/bootstrap, rsaKeySize) and provides sufficient strength for
// day-2 TLS material with regular rotation.
const serviceCSRKeySize = 2048

// CSRParams are parameters for service cert CSR generation.
type CSRParams struct {
	// CommonName is subject CN (required). For server TLS, typically matches
	// service/incarnation logical name.
	CommonName string
	// DNSNames are SAN names (optional). Empty list means SAN without DNS.
	DNSNames []string
}

// GeneratedCSR is result of [GenerateServiceCSR].
//
// ★ R2-EXCEPTION (cert-rotation Var1): PrivateKeyPEM is generated by Keeper
// centrally and LEAVES generation boundary (caller stores it in Vault via
// WriteKV). Intentional deviation from identity model invariant "private key
// never leaves host" (soul_seeds/009, ADR-018): here material is SERVICE cert
// (e.g., server TLS for Redis), already stored in Vault for manual rotate_tls.
// Solution fixed in separate cert-rotation ADR. Private key NOT written to PG
// (warrant registry) — only vault_ref + fingerprint + serial.
type GeneratedCSR struct {
	// PrivateKeyPEM is PKCS#8 PEM of private key. Caller MUST store it in Vault
	// and NEVER log / embed in audit-payload / return externally (secret-material).
	PrivateKeyPEM []byte
	// CSRPEM is PKCS#10 CSR PEM (carries only public key). Passed to
	// [Client.SignCSR].
	CSRPEM []byte
}

// GenerateServiceCSR generates RSA keypair and PKCS#10 service cert CSR.
// Private key stays in memory (in returned [GeneratedCSR.PrivateKeyPEM]);
// network/filesystem/Vault not touched — pure crypto function.
//
// Cert-rotation flow (keeper/internal/reaper/rotate_certs.go):
// GenerateServiceCSR → [Client.SignCSR] (Vault PKI) → [Client.WriteKV]
// (private key + cert to Vault) → INSERT warrant.
func GenerateServiceCSR(p CSRParams) (*GeneratedCSR, error) {
	if p.CommonName == "" {
		return nil, fmt.Errorf("vault csrgen: common_name is empty")
	}

	key, err := rsa.GenerateKey(rand.Reader, serviceCSRKeySize)
	if err != nil {
		return nil, fmt.Errorf("vault csrgen: generate rsa key: %w", err)
	}

	tmpl := x509.CertificateRequest{
		Subject:  pkix.Name{CommonName: p.CommonName},
		DNSNames: p.DNSNames,
	}
	der, err := x509.CreateCertificateRequest(rand.Reader, &tmpl, key)
	if err != nil {
		return nil, fmt.Errorf("vault csrgen: create CSR: %w", err)
	}
	csrPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE REQUEST", Bytes: der})

	// PKCS#8 is universal private key format (Redis/openssl read it same as
	// PKCS#1); single format for service certs simplifies Vault contract.
	keyDER, err := x509.MarshalPKCS8PrivateKey(key)
	if err != nil {
		return nil, fmt.Errorf("vault csrgen: marshal private key: %w", err)
	}
	keyPEM := pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: keyDER})

	return &GeneratedCSR{PrivateKeyPEM: keyPEM, CSRPEM: csrPEM}, nil
}
