#!/usr/bin/env python3
"""Checks the repository's internal markdown links.

Collects links of the form `[text](path.md)` and `[text](path.md#anchor)` from all
*.md files (including CLAUDE.md and examples/), as well as `docs/...#anchor` links
from Go comments, and checks:
  - the file exists at the relative path;
  - the anchor (if given) is generated by the GitHub slug of some heading
    in the target file.

GitHub slug: lowercase, non-alphanumeric characters (except space/hyphen/underscore)
are stripped, spaces -> hyphen; Cyrillic is preserved.

Pre-existing broken links outside the current scope are recorded in
scripts/doc-links-allowlist.txt (format `file:link`) and skipped.

External links (http/https/mailto), pure anchors (`#...` with no file),
non-markdown targets (`.go`, `.yaml`, `.yml`, images, etc.) - are outside the anchor
check (for non-md files only file existence is checked).
"""
from __future__ import annotations

import os
import re
import sys

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
ALLOWLIST_PATH = os.path.join(REPO_ROOT, "scripts", "doc-links-allowlist.txt")

# Directories we don't scan.
SKIP_DIRS = {".git", "node_modules", "vendor", ".pm", "proto/gen"}

MD_LINK_RE = re.compile(r"\[[^\]]*\]\(([^)\s]+?)\)")
# Go comments: catch docs/...#anchor or ../docs/...#anchor inside a line.
GO_DOC_LINK_RE = re.compile(r"(?:\.\./)*docs/[\w./-]+\.md#[\w.-]+")

HEADING_RE = re.compile(r"^(#{1,6})\s+(.*?)\s*#*\s*$")


def github_slug(text: str) -> str:
    s = text.strip().lower()
    # strip markdown formatting from the heading (backticks, *, _, [..](..)).
    s = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", s)  # [t](u) -> t
    s = s.replace("`", "").replace("*", "")
    s = re.sub(r"[^\w\s-]", "", s, flags=re.UNICODE)
    s = s.replace(" ", "-")
    return s


def collect_anchors(md_path: str) -> set[str]:
    anchors: set[str] = set()
    seen: dict[str, int] = {}
    try:
        with open(md_path, encoding="utf-8") as fh:
            in_fence = False
            for line in fh:
                stripped = line.strip()
                if stripped.startswith("```") or stripped.startswith("~~~"):
                    in_fence = not in_fence
                    continue
                if in_fence:
                    continue
                m = HEADING_RE.match(line.rstrip("\n"))
                if not m:
                    continue
                base = github_slug(m.group(2))
                if base in seen:
                    seen[base] += 1
                    anchors.add(f"{base}-{seen[base]}")
                else:
                    seen[base] = 0
                    anchors.add(base)
    except OSError:
        pass
    return anchors


def load_allowlist() -> set[str]:
    entries: set[str] = set()
    if not os.path.exists(ALLOWLIST_PATH):
        return entries
    with open(ALLOWLIST_PATH, encoding="utf-8") as fh:
        for raw in fh:
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            # strip the trailing comment after ` # `
            line = line.split(" #", 1)[0].strip()
            if line:
                entries.add(line)
    return entries


def iter_files() -> list[str]:
    out: list[str] = []
    for dirpath, dirnames, filenames in os.walk(REPO_ROOT):
        rel = os.path.relpath(dirpath, REPO_ROOT)
        parts = set(rel.split(os.sep))
        if parts & {".git", "node_modules", "vendor", ".pm"}:
            dirnames[:] = []
            continue
        if rel.replace(os.sep, "/").startswith("proto/gen"):
            dirnames[:] = []
            continue
        for name in filenames:
            if name.endswith(".md") or name.endswith(".go"):
                out.append(os.path.join(dirpath, name))
    return out


def is_external(target: str) -> bool:
    return (
        target.startswith("http://")
        or target.startswith("https://")
        or target.startswith("mailto:")
        or target.startswith("//")
    )


# Cache of anchors keyed by the target file's absolute path.
_anchor_cache: dict[str, set[str]] = {}


def anchors_for(path: str) -> set[str]:
    if path not in _anchor_cache:
        _anchor_cache[path] = collect_anchors(path)
    return _anchor_cache[path]


def check_link(src_file: str, target: str, root_relative: bool = False) -> str | None:
    """Returns the error text, or None if the link is valid/out of scope.

    root_relative=True - the path is resolved from the repo root (the semantics of
    doc links in Go comments: `docs/...` is counted from the root, not from the file's directory).
    """
    if is_external(target) or target.startswith("#"):
        return None

    path_part, _, anchor = target.partition("#")
    if not path_part:
        return None

    base = REPO_ROOT if root_relative else os.path.dirname(src_file)
    abs_target = os.path.normpath(os.path.join(base, path_part))

    # Fallback: some markdown files (.claude/agents/*, CLAUDE.md) write links
    # from the repo root rather than relative to their own directory. If the relative
    # resolution didn't find the file - try from the root.
    if not os.path.exists(abs_target) and not root_relative:
        alt = os.path.normpath(os.path.join(REPO_ROOT, path_part))
        if os.path.exists(alt):
            abs_target = alt

    if not os.path.exists(abs_target):
        return f"target file not found: {path_part}"

    # We only check the anchor for markdown files.
    if anchor and abs_target.endswith(".md"):
        if anchor not in anchors_for(abs_target):
            return f"anchor not found in {path_part}: #{anchor}"

    return None


def main() -> int:
    allowlist = load_allowlist()
    used_allow: set[str] = set()
    errors: list[str] = []

    for src_file in iter_files():
        rel_src = os.path.relpath(src_file, REPO_ROOT).replace(os.sep, "/")
        try:
            with open(src_file, encoding="utf-8") as fh:
                content = fh.read()
        except (OSError, UnicodeDecodeError):
            continue

        is_go = src_file.endswith(".go")
        if is_go:
            targets = GO_DOC_LINK_RE.findall(content)
        else:  # .md
            targets = MD_LINK_RE.findall(content)

        for target in targets:
            key = f"{rel_src}:{target}"
            if key in allowlist:
                used_allow.add(key)
                continue
            err = check_link(src_file, target, root_relative=is_go)
            if err:
                errors.append(f"{rel_src}: {err}  (link: {target})")

    stale = allowlist - used_allow
    if errors:
        print("check-doc-links: found broken links:\n")
        for e in sorted(errors):
            print(f"  {e}")
        print(f"\nTOTAL broken links: {len(errors)}")
        if stale:
            print(f"({len(stale)} stale entries in the allowlist - see below)")
        return 1

    if stale:
        print("check-doc-links: links are intact, but the allowlist has stale entries")
        print("(link fixed/removed - remove the line from scripts/doc-links-allowlist.txt):\n")
        for s in sorted(stale):
            print(f"  {s}")
        return 1

    print(f"check-doc-links: all internal links are intact (allowlist: {len(allowlist)})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
