#!/usr/bin/env bash
# Version-aware generator of the catalog of VALID redis.conf directives (MVP, architect
# 2026-06-26). The result is COMMITTED data in essence (key redis_directives), NOT a
# runtime dependency: the script is run manually by the service author when adding a new
# supported Redis version, its output gets pasted into examples/service/redis/essence/
# _default.yaml. There is no network on the render path - assert reads the already-committed catalog.
#
# SOURCE OF TRUTH - the Redis upstream src/config.c (the standardConfig table via the
# createXConfig macros + special directives parsed in the body of loadServerConfigFromString).
# The redis.conf file as a source was REJECTED: prose comments (`# Note that ...`)
# are indistinguishable by regex from commented-out directive examples (`# maxmemory <bytes>`) ->
# hundreds of false "directives" (English words). config.c gives directive NAMES precisely.
#
# Each version -> a FLAT set of directive NAMES (MVP: names only, not values).
# The catalog key is the major.minor series (directives are stable within a patch series, evolution
# happens between minors). input.version (a distro pin like 5:7.0.15-1~deb12u7) is mapped to the key
# by extracting X.Y in scenario-assert.
#
# Usage:
#   scripts/gen-redis-catalog.sh                       # default series (below)
#   scripts/gen-redis-catalog.sh 7.0.15 8.0.6          # explicit tags
# Output - a YAML fragment redis_directives: on stdout (paste into essence/_default.yaml).

set -euo pipefail

# Canonical tags (latest patch of the series) for the versions supported by the service. Cross-checked
# against `git ls-remote --tags https://github.com/redis/redis` (2026-06-28): the real series
# covered by the service's version enum - 6.2/7.0/7.2/7.4/8.0/8.2/8.4/8.6. The tags below are the latest
# patch of each series at the time of the check (directives are stable within a patch series).
DEFAULT_TAGS=(6.2.22 7.0.15 7.2.14 7.4.9 8.0.6 8.2.7 8.4.4 8.6.4)

# Special directives parsed in config.c OUTSIDE the standardConfig table (in the body of
# loadServerConfigFromString via !strcasecmp). Real redis.conf directives that
# the operator can pass through redis_settings, but which are not declared via the createXConfig macro.
# Cross-checked against config.c 7.0/8.0/8.2: these six names are stable.
SPECIAL_DIRECTIVES=(slaveof include loadmodule rename-command user sentinel)

tags=("$@")
[ ${#tags[@]} -eq 0 ] && tags=("${DEFAULT_TAGS[@]}")

base_url="https://raw.githubusercontent.com/redis/redis"

echo "# GENERATED by scripts/gen-redis-catalog.sh from the Redis upstream src/config.c."
echo "# DO NOT edit by hand - regenerate with the script when adding a version."
echo "# Source tags: ${tags[*]}"
echo "redis_directives:"

for tag in "${tags[@]}"; do
  series="${tag%.*}"   # 7.0.15 -> 7.0
  cfg="$(curl -sf "$base_url/$tag/src/config.c")" || {
    echo "ERROR: failed to download config.c for tag $tag" >&2
    exit 1
  }

  {
    # The 1st argument of createXConfig - the canonical directive name.
    printf '%s\n' "$cfg" | grep -oE 'create[A-Za-z]+Config\("[a-z][a-zA-Z0-9_-]*"' \
      | sed -E 's/.*\("([^"]*)"$/\1/'
    # The 2nd argument (alias) - an optional synonym (e.g. slaveof for replicaof,
    # *-ziplist-* for *-listpack-*). We only take non-empty ones (quoted).
    printf '%s\n' "$cfg" | grep -oE 'create[A-Za-z]+Config\("[a-z][a-zA-Z0-9_-]*",[[:space:]]*"[a-z][a-zA-Z0-9_-]*"' \
      | sed -E 's/.*,[[:space:]]*"([^"]*)"$/\1/'
    # Special directives outside the table.
    printf '%s\n' "${SPECIAL_DIRECTIVES[@]}"
  } | sort -u | {
    echo "  \"$series\":"
    while IFS= read -r name; do
      [ -n "$name" ] && echo "    - $name"
    done
  }
done
