package cert

import (
	"fmt"
	"time"

	keepercert "github.com/souls-guild/soul-stack/keeper/internal/cert"
	"github.com/souls-guild/soul-stack/keeper/internal/certissue"
	"github.com/souls-guild/soul-stack/keeper/internal/coremod/util"
	"github.com/souls-guild/soul-stack/shared/audit"

	pluginv1 "github.com/souls-guild/soul-stack/proto/plugin/gen/go/v1"
	"google.golang.org/grpc"
)

// applyIssued implements state `core.cert.issued` (NIM-99 Slice C): Keeper ITSELF
// issues the incarnation's server TLS cert - generates keypair+CSR, signs
// via Vault PKI with the role FROM THE MANIFEST (not from params), puts cert+key in Vault
// under E3 paths, and registers active Warrant rows (cert + key companion).
//
// SECURITY (R2 invariant): the private key is generated by Keeper and lives only in
// Vault - it does NOT leak into output/audit/error text (certissue already guarantees
// this, and we don't put it out either).
func applyIssued(m *Module, req *pluginv1.ApplyRequest, stream grpc.ServerStreamingServer[pluginv1.ApplyEvent]) error {
	ctx := stream.Context()

	if m.Signer == nil || m.VaultWriter == nil || m.Policy == nil || m.CSRGen == nil || m.PKIMount == nil {
		return util.SendFailed(stream, "core.cert.issued: module not configured (no PKI-signer/policy)")
	}

	incarnation, err := util.StringParam(req.Params, "incarnation")
	if err != nil {
		return util.SendFailed(stream, err.Error())
	}

	// auto_rotate - flag to enroll in Reaper auto-rotation; default yes.
	autoRotate, hasAuto, err := util.OptBoolParam(req.Params, "auto_rotate")
	if err != nil {
		return util.SendFailed(stream, err.Error())
	}
	if !hasAuto {
		autoRotate = true
	}

	pol, err := m.Policy.Resolve(ctx, incarnation)
	if err != nil {
		return util.SendFailed(stream, err.Error())
	}
	if !pol.Enabled {
		return util.SendFailed(stream, "certificate_rotation missing/disabled for the service - issuance not possible")
	}
	if pol.PKIRole == "" {
		return util.SendFailed(stream, "certificate_rotation: pki_role not set in the manifest - issuance not possible")
	}
	// Fail-fast on a nonexistent scenario (mirrors the reaper membership check): otherwise
	// the cert enrolls with auto_rotate=true, and the rotator silently skips it -> silent expiry.
	if pol.Scenario == "" || !scenarioKnown(pol.Scenario, pol.KnownScenarios) {
		return util.SendFailed(stream, fmt.Sprintf("core.cert.issued: rotation scenario %q not found in the service (declare scenario/%s/ or fix certificate_rotation.scenario)", pol.Scenario, pol.Scenario))
	}

	mount := m.PKIMount()

	// Signing role - pol.PKIRole (MANIFEST), Vault paths - by service from the policy.
	mat, err := certissue.Issue(ctx, m.Signer, m.VaultWriter, m.CSRGen, certissue.Params{
		CommonName: incarnation + ".tls",
		DNSNames:   []string{incarnation + ".tls", incarnation},
		Mount:      mount,
		Role:       pol.PKIRole,
		CertPath:   certissue.VaultPath(pol.Service, incarnation, keepercert.KindCert),
		KeyPath:    certissue.VaultPath(pol.Service, incarnation, keepercert.KindKey),
	})
	if err != nil {
		return util.SendFailed(stream, err.Error())
	}

	certWarrant := &keepercert.Warrant{
		IncarnationID: incarnation,
		Kind:          keepercert.KindCert,
		VaultRef:      mat.CertRef,
		SerialNumber:  mat.SerialNumber,
		Fingerprint:   mat.Fingerprint,
		NotAfter:      mat.NotAfter,
		Status:        keepercert.StatusActive,
		AutoRotate:    autoRotate,
		PKIMount:      &mount,
		PKIRole:       &pol.PKIRole,
	}
	if m.KID != "" {
		certWarrant.IssuedByKID = &m.KID
	}
	// cert+key in different tx; reaper drives off the cert row, desync self-heals on retry (review M3)
	if regErr := m.Store.RegisterActive(ctx, certWarrant); regErr != nil {
		return util.SendFailed(stream, fmt.Sprintf("register cert: %v", regErr))
	}

	// key companion: the private key was updated together with cert; it is NOT the rotation driver itself
	// (auto_rotate=false - Reaper doesn't scan it). Same fingerprint/serial/
	// not_after (one pair).
	keyWarrant := &keepercert.Warrant{
		IncarnationID: incarnation,
		Kind:          keepercert.KindKey,
		VaultRef:      mat.KeyRef,
		SerialNumber:  mat.SerialNumber,
		Fingerprint:   mat.Fingerprint,
		NotAfter:      mat.NotAfter,
		Status:        keepercert.StatusActive,
		AutoRotate:    false,
	}
	if m.KID != "" {
		keyWarrant.IssuedByKID = &m.KID
	}
	if regErr := m.Store.RegisterActive(ctx, keyWarrant); regErr != nil {
		return util.SendFailed(stream, fmt.Sprintf("register key: %v", regErr))
	}

	// Audit best-effort (nil-audit ok); only NON-secret metadata.
	if m.Audit != nil {
		ev := &audit.Event{
			EventType:     audit.EventCertIssued,
			Source:        audit.SourceKeeperInternal,
			CorrelationID: incarnation,
			Payload: map[string]any{
				"incarnation":   incarnation,
				"kind":          string(keepercert.KindCert),
				"fingerprint":   mat.Fingerprint,
				"serial_number": mat.SerialNumber,
				"not_after":     mat.NotAfter.UTC().Format(time.RFC3339),
			},
		}
		_ = m.Audit.Write(ctx, ev)
	}

	out := map[string]any{
		"registered_kinds": []any{string(keepercert.KindCert), string(keepercert.KindKey)},
		"fingerprint":      mat.Fingerprint,
		"serial_number":    mat.SerialNumber,
		"not_after":        mat.NotAfter.UTC().Format(time.RFC3339),
	}
	return util.SendFinal(stream, true, out)
}

// scenarioKnown - scenario membership among the scenario/ snapshot (mirrors the reaper check).
func scenarioKnown(scenario string, known []string) bool {
	for _, s := range known {
		if s == scenario {
			return true
		}
	}
	return false
}
